import { UnifiedPersona } from '@shared/mockupTypes';

export const BABY_PERSONAS: UnifiedPersona[] = [
  {
    id: 'baby-male-white-xs-01',
    name: 'Oliver',
    age: '8 months',
    sex: 'Male',
    ethnicity: 'White',
    size: 'XS',
    height: "27\"",
    weight: '18 lbs',
    build: 'chubby baby',
    facialFeatures: 'round cheeks, button nose',
    hairStyle: 'fine wispy hair',
    hairColor: 'light brown',
    eyeColor: 'blue',
    skinTone: 'fair pink',
    fullDescription: 'Adorable 8-month-old baby boy with round cheeks and a button nose. Fine wispy light brown hair tops his head, with bright blue eyes full of wonder.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-white-xs-01_oliver_headshot.png'
  },
  {
    id: 'baby-male-black-xs-01',
    name: 'Jayden',
    age: '10 months',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'XS',
    height: "28\"",
    weight: '20 lbs',
    build: 'healthy baby',
    facialFeatures: 'wide eyes, happy expression',
    hairStyle: 'soft curly',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Happy 10-month-old baby boy with wide curious eyes and a cheerful expression. Soft curly black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-black-xs-01_jayden_headshot.png'
  },
  {
    id: 'baby-male-hispanic-xs-01',
    name: 'Mateo',
    age: '9 months',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'XS',
    height: "27\"",
    weight: '19 lbs',
    build: 'chubby baby',
    facialFeatures: 'dimpled cheeks, curious look',
    hairStyle: 'thick dark hair',
    hairColor: 'black',
    eyeColor: 'brown',
    skinTone: 'warm tan',
    fullDescription: 'Curious 9-month-old baby boy with adorable dimpled cheeks. Thick dark hair and expressive brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-hispanic-xs-01_mateo_headshot.png'
  },
  {
    id: 'baby-male-asian-xs-01',
    name: 'Leo',
    age: '7 months',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'healthy baby',
    facialFeatures: 'round face, calm expression',
    hairStyle: 'straight fine hair',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Peaceful 7-month-old baby boy with a round face and calm demeanor. Straight fine black hair and observant dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-asian-xs-01_leo_headshot.png'
  },
  {
    id: 'baby-male-indian-xs-01',
    name: 'Arjun',
    age: '11 months',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'XS',
    height: "28\"",
    weight: '21 lbs',
    build: 'healthy baby',
    facialFeatures: 'bright eyes, playful smile',
    hairStyle: 'thick wavy',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Playful 11-month-old baby boy with bright eyes and an engaging smile. Thick wavy black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-indian-xs-01_arjun_headshot.png'
  },
  {
    id: 'baby-male-southeast-asian-xs-01',
    name: 'Kai',
    age: '8 months',
    sex: 'Male',
    ethnicity: 'Southeast Asian',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'chubby baby',
    facialFeatures: 'chubby cheeks, alert eyes',
    hairStyle: 'fine straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    fullDescription: 'Alert 8-month-old baby boy with chubby cheeks and observant eyes. Fine straight black hair and curious dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-southeast-asian-xs-01_kai_headshot.png'
  },
  {
    id: 'baby-male-middle-eastern-xs-01',
    name: 'Omar',
    age: '9 months',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'XS',
    height: "27\"",
    weight: '19 lbs',
    build: 'healthy baby',
    facialFeatures: 'expressive face, long lashes',
    hairStyle: 'thick dark',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Expressive 9-month-old baby boy with striking long lashes. Thick dark hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-middle-eastern-xs-01_omar_headshot.png'
  },
  {
    id: 'baby-male-indigenous-xs-01',
    name: 'River',
    age: '10 months',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'XS',
    height: "28\"",
    weight: '20 lbs',
    build: 'healthy baby',
    facialFeatures: 'round face, bright smile',
    hairStyle: 'thick straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Cheerful 10-month-old baby boy with a round face and bright smile. Thick straight black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-indigenous-xs-01_river_headshot.png'
  },
  {
    id: 'baby-male-diverse-xs-01',
    name: 'Noah',
    age: '8 months',
    sex: 'Male',
    ethnicity: 'Diverse',
    size: 'XS',
    height: "27\"",
    weight: '18 lbs',
    build: 'chubby baby',
    facialFeatures: 'mixed features, happy expression',
    hairStyle: 'soft curls',
    hairColor: 'dark brown',
    eyeColor: 'hazel',
    skinTone: 'warm caramel',
    fullDescription: 'Happy 8-month-old baby boy with beautifully blended features. Soft curly dark brown hair and striking hazel eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-male-diverse-xs-01_noah_headshot.png'
  },
  {
    id: 'baby-female-white-xs-01',
    name: 'Emma',
    age: '9 months',
    sex: 'Female',
    ethnicity: 'White',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'petite baby',
    facialFeatures: 'delicate features, sweet smile',
    hairStyle: 'fine wispy',
    hairColor: 'blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Sweet 9-month-old baby girl with delicate features and a gentle smile. Fine wispy blonde hair and bright blue eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-white-xs-01_emma_headshot.png'
  },
  {
    id: 'baby-female-black-xs-01',
    name: 'Zoe',
    age: '10 months',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'XS',
    height: "27\"",
    weight: '18 lbs',
    build: 'healthy baby',
    facialFeatures: 'bright eyes, joyful expression',
    hairStyle: 'natural curls',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'deep brown',
    fullDescription: 'Joyful 10-month-old baby girl with bright expressive eyes. Beautiful natural curls and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-black-xs-01_zoe_headshot.png'
  },
  {
    id: 'baby-female-hispanic-xs-01',
    name: 'Sofia',
    age: '8 months',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'chubby baby',
    facialFeatures: 'rosy cheeks, sweet expression',
    hairStyle: 'dark wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm olive',
    fullDescription: 'Sweet 8-month-old baby girl with rosy cheeks and an endearing expression. Dark wavy hair and warm brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-hispanic-xs-01_sofia_headshot.png'
  },
  {
    id: 'baby-female-asian-xs-01',
    name: 'Mei',
    age: '7 months',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'XS',
    height: "25\"",
    weight: '15 lbs',
    build: 'petite baby',
    facialFeatures: 'round face, peaceful look',
    hairStyle: 'fine straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Peaceful 7-month-old baby girl with a round face and serene expression. Fine straight black hair and calm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-asian-xs-01_mei_headshot.png'
  },
  {
    id: 'baby-female-indian-xs-01',
    name: 'Asha',
    age: '11 months',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'XS',
    height: "27\"",
    weight: '19 lbs',
    build: 'healthy baby',
    facialFeatures: 'big eyes, cheerful',
    hairStyle: 'thick dark',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Cheerful 11-month-old baby girl with big expressive eyes. Thick dark hair and sparkling dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-indian-xs-01_asha_headshot.png'
  },
  {
    id: 'baby-female-southeast-asian-xs-01',
    name: 'Linh',
    age: '9 months',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'XS',
    height: "26\"",
    weight: '16 lbs',
    build: 'petite baby',
    facialFeatures: 'sweet face, gentle smile',
    hairStyle: 'fine dark',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light tan',
    fullDescription: 'Gentle 9-month-old baby girl with a sweet face and soft smile. Fine dark hair and attentive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-southeast-asian-xs-01_linh_headshot.png'
  },
  {
    id: 'baby-female-middle-eastern-xs-01',
    name: 'Layla',
    age: '10 months',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'XS',
    height: "27\"",
    weight: '18 lbs',
    build: 'healthy baby',
    facialFeatures: 'large eyes, long lashes',
    hairStyle: 'thick wavy',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Beautiful 10-month-old baby girl with large expressive eyes and long lashes. Thick wavy black hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-middle-eastern-xs-01_layla_headshot.png'
  },
  {
    id: 'baby-female-indigenous-xs-01',
    name: 'Luna',
    age: '8 months',
    sex: 'Female',
    ethnicity: 'Indigenous',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'healthy baby',
    facialFeatures: 'round cheeks, bright eyes',
    hairStyle: 'thick straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Bright-eyed 8-month-old baby girl with round cheeks and an engaging presence. Thick straight black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-indigenous-xs-01_luna_headshot.png'
  },
  {
    id: 'baby-female-diverse-xs-01',
    name: 'Mia',
    age: '9 months',
    sex: 'Female',
    ethnicity: 'Diverse',
    size: 'XS',
    height: "26\"",
    weight: '17 lbs',
    build: 'healthy baby',
    facialFeatures: 'mixed features, radiant smile',
    hairStyle: 'soft curls',
    hairColor: 'brown',
    eyeColor: 'green-brown',
    skinTone: 'golden',
    fullDescription: 'Radiant 9-month-old baby girl with beautifully blended features. Soft curly brown hair and unique green-brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/baby-female-diverse-xs-01_mia_headshot.png'
  }
];
