import { UnifiedPersona } from '@shared/mockupTypes';

export const KIDS_PERSONAS: UnifiedPersona[] = [
  {
    id: 'kids-male-white-s-01',
    name: 'Jack',
    age: '8',
    sex: 'Male',
    ethnicity: 'White',
    size: 'S',
    height: "4'2\"",
    weight: '55 lbs',
    build: 'athletic',
    facialFeatures: 'freckles, friendly smile',
    hairStyle: 'short messy',
    hairColor: 'light brown',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Energetic 8-year-old boy with a friendly smile and light freckles. Short messy light brown hair and bright blue eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-white-s-01_jack_headshot.png'
  },
  {
    id: 'kids-male-black-s-01',
    name: 'Jaylen',
    age: '9',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'S',
    height: "4'4\"",
    weight: '60 lbs',
    build: 'athletic',
    facialFeatures: 'confident expression, bright smile',
    hairStyle: 'short fade',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Confident 9-year-old boy with a bright smile. Neat short fade haircut and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-black-s-01_jaylen_headshot.png'
  },
  {
    id: 'kids-male-hispanic-s-01',
    name: 'Miguel',
    age: '7',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'S',
    height: "4'0\"",
    weight: '50 lbs',
    build: 'lean',
    facialFeatures: 'playful expression, dimples',
    hairStyle: 'wavy medium',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm tan',
    fullDescription: 'Playful 7-year-old boy with a mischievous grin and cute dimples. Wavy dark brown hair and sparkling brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-hispanic-s-01_miguel_headshot.png'
  },
  {
    id: 'kids-male-asian-s-01',
    name: 'Ryan',
    age: '8',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'S',
    height: "4'1\"",
    weight: '52 lbs',
    build: 'slim',
    facialFeatures: 'studious look, neat appearance',
    hairStyle: 'straight short',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Studious 8-year-old boy with a neat appearance. Straight short black hair and observant dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-asian-s-01_ryan_headshot.png'
  },
  {
    id: 'kids-male-indian-s-01',
    name: 'Aarav',
    age: '9',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'S',
    height: "4'3\"",
    weight: '58 lbs',
    build: 'average',
    facialFeatures: 'friendly expression, bright eyes',
    hairStyle: 'thick wavy',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Friendly 9-year-old boy with bright expressive eyes. Thick wavy black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-indian-s-01_aarav_headshot.png'
  },
  {
    id: 'kids-male-southeast-asian-s-01',
    name: 'Bao',
    age: '7',
    sex: 'Male',
    ethnicity: 'Southeast Asian',
    size: 'S',
    height: "4'0\"",
    weight: '48 lbs',
    build: 'slim',
    facialFeatures: 'cheerful expression',
    hairStyle: 'short spiky',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    fullDescription: 'Cheerful 7-year-old boy with an infectious smile. Short spiky black hair and bright dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-southeast-asian-s-01_bao_headshot.png'
  },
  {
    id: 'kids-male-middle-eastern-s-01',
    name: 'Yusuf',
    age: '8',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'S',
    height: "4'2\"",
    weight: '54 lbs',
    build: 'average',
    facialFeatures: 'expressive eyes, gentle smile',
    hairStyle: 'thick curly',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Gentle 8-year-old boy with expressive eyes. Thick curly black hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-middle-eastern-s-01_yusuf_headshot.png'
  },
  {
    id: 'kids-male-indigenous-s-01',
    name: 'Hawk',
    age: '9',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'S',
    height: "4'4\"",
    weight: '58 lbs',
    build: 'athletic',
    facialFeatures: 'strong features, warm smile',
    hairStyle: 'long straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Athletic 9-year-old boy with strong features and a warm smile. Long straight black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-indigenous-s-01_hawk_headshot.png'
  },
  {
    id: 'kids-male-diverse-s-01',
    name: 'Jordan',
    age: '8',
    sex: 'Male',
    ethnicity: 'Diverse',
    size: 'S',
    height: "4'2\"",
    weight: '55 lbs',
    build: 'athletic',
    facialFeatures: 'mixed features, friendly smile',
    hairStyle: 'curly medium',
    hairColor: 'brown',
    eyeColor: 'hazel',
    skinTone: 'golden',
    fullDescription: 'Friendly 8-year-old boy with beautifully blended features. Curly brown hair and striking hazel eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-male-diverse-s-01_jordan_headshot.png'
  },
  {
    id: 'kids-female-white-s-01',
    name: 'Sophie',
    age: '8',
    sex: 'Female',
    ethnicity: 'White',
    size: 'S',
    height: "4'1\"",
    weight: '52 lbs',
    build: 'slim',
    facialFeatures: 'sweet expression, freckles',
    hairStyle: 'long braided',
    hairColor: 'red',
    eyeColor: 'green',
    skinTone: 'fair',
    fullDescription: 'Sweet 8-year-old girl with light freckles and a gentle smile. Long red hair in braids and sparkling green eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-white-s-01_sophie_headshot.png'
  },
  {
    id: 'kids-female-black-s-01',
    name: 'Aisha',
    age: '9',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'S',
    height: "4'3\"",
    weight: '58 lbs',
    build: 'athletic',
    facialFeatures: 'bright smile, confident expression',
    hairStyle: 'braided buns',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'deep brown',
    fullDescription: 'Confident 9-year-old girl with a bright smile. Beautiful black hair in braided buns and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-black-s-01_aisha_headshot.png'
  },
  {
    id: 'kids-female-hispanic-s-01',
    name: 'Camila',
    age: '7',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'S',
    height: "3'11\"",
    weight: '48 lbs',
    build: 'petite',
    facialFeatures: 'dimples, cheerful expression',
    hairStyle: 'long wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'olive',
    fullDescription: 'Cheerful 7-year-old girl with cute dimples. Long wavy dark brown hair and warm brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-hispanic-s-01_camila_headshot.png'
  },
  {
    id: 'kids-female-asian-s-01',
    name: 'Emily',
    age: '8',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'S',
    height: "4'0\"",
    weight: '50 lbs',
    build: 'slim',
    facialFeatures: 'delicate features, studious look',
    hairStyle: 'ponytail',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Studious 8-year-old girl with delicate features. Black hair in a neat ponytail and thoughtful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-asian-s-01_emily_headshot.png'
  },
  {
    id: 'kids-female-indian-s-01',
    name: 'Ananya',
    age: '9',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'S',
    height: "4'2\"",
    weight: '55 lbs',
    build: 'average',
    facialFeatures: 'big eyes, warm smile',
    hairStyle: 'long braided',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Warm 9-year-old girl with big expressive eyes. Long black hair in a neat braid and sparkling dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-indian-s-01_ananya_headshot.png'
  },
  {
    id: 'kids-female-southeast-asian-s-01',
    name: 'Thao',
    age: '7',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'S',
    height: "3'10\"",
    weight: '45 lbs',
    build: 'petite',
    facialFeatures: 'gentle expression, sweet smile',
    hairStyle: 'short bob',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light tan',
    fullDescription: 'Gentle 7-year-old girl with a sweet smile. Black hair in a short bob and attentive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-southeast-asian-s-01_thao_headshot.png'
  },
  {
    id: 'kids-female-middle-eastern-s-01',
    name: 'Leila',
    age: '8',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'S',
    height: "4'1\"",
    weight: '52 lbs',
    build: 'average',
    facialFeatures: 'large eyes, long lashes',
    hairStyle: 'long curly',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Beautiful 8-year-old girl with large expressive eyes and long lashes. Long curly dark brown hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-middle-eastern-s-01_leila_headshot.png'
  },
  {
    id: 'kids-female-indigenous-s-01',
    name: 'Sky',
    age: '9',
    sex: 'Female',
    ethnicity: 'Indigenous',
    size: 'S',
    height: "4'3\"",
    weight: '56 lbs',
    build: 'athletic',
    facialFeatures: 'bright eyes, confident smile',
    hairStyle: 'two braids',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Confident 9-year-old girl with bright eyes. Long black hair in two neat braids and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-indigenous-s-01_sky_headshot.png'
  },
  {
    id: 'kids-female-diverse-s-01',
    name: 'Maya',
    age: '8',
    sex: 'Female',
    ethnicity: 'Diverse',
    size: 'S',
    height: "4'1\"",
    weight: '53 lbs',
    build: 'average',
    facialFeatures: 'mixed features, radiant smile',
    hairStyle: 'natural curls',
    hairColor: 'brown',
    eyeColor: 'amber',
    skinTone: 'caramel',
    fullDescription: 'Radiant 8-year-old girl with beautifully blended features. Natural brown curls and unique amber eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/kids-female-diverse-s-01_maya_headshot.png'
  }
];
