import { UnifiedPersona } from '@shared/mockupTypes';

export const SENIOR_PERSONAS: UnifiedPersona[] = [
  {
    id: 'senior-male-white-l-01',
    name: 'Robert',
    age: '68',
    sex: 'Male',
    ethnicity: 'White',
    size: 'L',
    height: "5'10\"",
    weight: '185 lbs',
    build: 'sturdy',
    facialFeatures: 'distinguished gray hair, kind eyes',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Distinguished 68-year-old man with kind eyes and a warm demeanor. Short gray hair and wise blue eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-white-l-01_robert_headshot.png'
  },
  {
    id: 'senior-male-black-l-01',
    name: 'Harold',
    age: '72',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'L',
    height: "5'11\"",
    weight: '190 lbs',
    build: 'solid',
    facialFeatures: 'dignified expression, gray beard',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Dignified 72-year-old man with a neat gray beard. Short gray hair and warm dark brown eyes full of wisdom.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-black-l-01_harold_headshot.png'
  },
  {
    id: 'senior-male-hispanic-l-01',
    name: 'Antonio',
    age: '65',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'L',
    height: "5'8\"",
    weight: '175 lbs',
    build: 'average',
    facialFeatures: 'warm smile, salt-and-pepper mustache',
    hairStyle: 'wavy gray',
    hairColor: 'salt-and-pepper',
    eyeColor: 'brown',
    skinTone: 'tan',
    fullDescription: 'Warm 65-year-old man with a friendly smile and neat salt-and-pepper mustache. Wavy graying hair and kind brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-hispanic-l-01_antonio_headshot.png'
  },
  {
    id: 'senior-male-asian-l-01',
    name: 'Chen',
    age: '70',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'L',
    height: "5'7\"",
    weight: '165 lbs',
    build: 'lean',
    facialFeatures: 'wise expression, gentle smile',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Wise 70-year-old man with a gentle smile. Short gray hair and thoughtful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-asian-l-01_chen_headshot.png'
  },
  {
    id: 'senior-male-indian-l-01',
    name: 'Vijay',
    age: '67',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'L',
    height: "5'9\"",
    weight: '175 lbs',
    build: 'average',
    facialFeatures: 'kind expression, gray beard',
    hairStyle: 'thinning gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Kind 67-year-old man with a neat gray beard. Thinning gray hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-indian-l-01_vijay_headshot.png'
  },
  {
    id: 'senior-male-southeast-asian-l-01',
    name: 'Tran',
    age: '69',
    sex: 'Male',
    ethnicity: 'Southeast Asian',
    size: 'L',
    height: "5'6\"",
    weight: '155 lbs',
    build: 'slim',
    facialFeatures: 'serene expression',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    fullDescription: 'Serene 69-year-old man with a calm demeanor. Short gray hair and peaceful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-southeast-asian-l-01_tran_headshot.png'
  },
  {
    id: 'senior-male-middle-eastern-l-01',
    name: 'Karim',
    age: '66',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'L',
    height: "5'10\"",
    weight: '180 lbs',
    build: 'solid',
    facialFeatures: 'distinguished beard, wise eyes',
    hairStyle: 'gray swept back',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Distinguished 66-year-old man with a full gray beard. Gray hair swept back and wise dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-middle-eastern-l-01_karim_headshot.png'
  },
  {
    id: 'senior-male-indigenous-l-01',
    name: 'Joseph',
    age: '71',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'L',
    height: "5'9\"",
    weight: '175 lbs',
    build: 'sturdy',
    facialFeatures: 'weathered features, wise expression',
    hairStyle: 'long gray braided',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Wise 71-year-old man with weathered features. Long gray hair in traditional braids and knowing dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-indigenous-l-01_joseph_headshot.png'
  },
  {
    id: 'senior-male-diverse-l-01',
    name: 'James',
    age: '68',
    sex: 'Male',
    ethnicity: 'Diverse',
    size: 'L',
    height: "5'10\"",
    weight: '180 lbs',
    build: 'average',
    facialFeatures: 'mixed heritage features, warm smile',
    hairStyle: 'curly gray',
    hairColor: 'gray',
    eyeColor: 'hazel',
    skinTone: 'light brown',
    fullDescription: 'Warm 68-year-old man with beautifully blended heritage features. Curly gray hair and wise hazel eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-male-diverse-l-01_james_headshot.png'
  },
  {
    id: 'senior-female-white-l-01',
    name: 'Margaret',
    age: '67',
    sex: 'Female',
    ethnicity: 'White',
    size: 'L',
    height: "5'5\"",
    weight: '155 lbs',
    build: 'average',
    facialFeatures: 'elegant features, warm smile',
    hairStyle: 'short silver bob',
    hairColor: 'silver',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Elegant 67-year-old woman with a warm smile. Short silver bob and sparkling blue eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-white-l-01_margaret_headshot.png'
  },
  {
    id: 'senior-female-black-l-01',
    name: 'Dorothy',
    age: '70',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'L',
    height: "5'6\"",
    weight: '160 lbs',
    build: 'solid',
    facialFeatures: 'graceful features, radiant smile',
    hairStyle: 'short natural gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Graceful 70-year-old woman with a radiant smile. Short natural gray hair and warm dark brown eyes full of wisdom.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-black-l-01_dorothy_headshot.png'
  },
  {
    id: 'senior-female-hispanic-l-01',
    name: 'Rosa',
    age: '66',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'L',
    height: "5'4\"",
    weight: '150 lbs',
    build: 'average',
    facialFeatures: 'warm expression, kind eyes',
    hairStyle: 'medium gray wavy',
    hairColor: 'salt-and-pepper',
    eyeColor: 'brown',
    skinTone: 'tan',
    fullDescription: 'Warm 66-year-old woman with kind eyes. Medium-length wavy salt-and-pepper hair and gentle brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-hispanic-l-01_rosa_headshot.png'
  },
  {
    id: 'senior-female-asian-l-01',
    name: 'Mei Lin',
    age: '69',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'L',
    height: "5'3\"",
    weight: '140 lbs',
    build: 'petite',
    facialFeatures: 'serene expression, gentle smile',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Serene 69-year-old woman with a gentle smile. Short gray hair and peaceful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-asian-l-01_mei-lin_headshot.png'
  },
  {
    id: 'senior-female-indian-l-01',
    name: 'Lakshmi',
    age: '68',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'L',
    height: "5'4\"",
    weight: '150 lbs',
    build: 'average',
    facialFeatures: 'graceful features, warm eyes',
    hairStyle: 'long gray braided',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Graceful 68-year-old woman with warm eyes. Long gray hair in a neat braid and gentle dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-indian-l-01_lakshmi_headshot.png'
  },
  {
    id: 'senior-female-southeast-asian-l-01',
    name: 'Nguyen',
    age: '65',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'L',
    height: "5'2\"",
    weight: '135 lbs',
    build: 'petite',
    facialFeatures: 'calm expression, gentle smile',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    fullDescription: 'Calm 65-year-old woman with a gentle smile. Short gray hair and serene dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-southeast-asian-l-01_nguyen_headshot.png'
  },
  {
    id: 'senior-female-middle-eastern-l-01',
    name: 'Fatima',
    age: '67',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'L',
    height: "5'5\"",
    weight: '155 lbs',
    build: 'average',
    facialFeatures: 'elegant features, wise eyes',
    hairStyle: 'medium gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Elegant 67-year-old woman with wise eyes. Medium-length gray hair and knowing dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-middle-eastern-l-01_fatima_headshot.png'
  },
  {
    id: 'senior-female-indigenous-l-01',
    name: 'Grace',
    age: '70',
    sex: 'Female',
    ethnicity: 'Indigenous',
    size: 'L',
    height: "5'4\"",
    weight: '150 lbs',
    build: 'sturdy',
    facialFeatures: 'weathered beauty, wise expression',
    hairStyle: 'long gray braided',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Wise 70-year-old woman with beautiful weathered features. Long gray hair in traditional braids and knowing dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-indigenous-l-01_grace_headshot.png'
  },
  {
    id: 'senior-female-diverse-l-01',
    name: 'Patricia',
    age: '68',
    sex: 'Female',
    ethnicity: 'Diverse',
    size: 'L',
    height: "5'5\"",
    weight: '155 lbs',
    build: 'average',
    facialFeatures: 'mixed heritage features, radiant smile',
    hairStyle: 'curly gray',
    hairColor: 'gray',
    eyeColor: 'hazel',
    skinTone: 'light brown',
    fullDescription: 'Radiant 68-year-old woman with beautifully blended heritage features. Curly gray hair and warm hazel eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/senior-female-diverse-l-01_patricia_headshot.png'
  }
];
