import { UnifiedPersona } from '@shared/mockupTypes';

export const SENIOR_PERSONAS: UnifiedPersona[] = [
  {
    id: 'senior-male-white-m-01',
    name: 'Robert',
    age: '62',
    sex: 'Male',
    ethnicity: 'White',
    size: 'M',
    height: "5'10\"",
    weight: '175 lbs',
    build: 'average',
    facialFeatures: 'distinguished gray temples, laugh lines, clean-shaven',
    hairStyle: 'short and neat',
    hairColor: 'salt and pepper',
    eyeColor: 'blue',
    skinTone: 'fair with mature complexion',
    fullDescription: 'Distinguished 62-year-old man with salt and pepper hair neatly styled. His blue eyes convey wisdom and warmth, with laugh lines that speak to a life well-lived.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-white-l-01',
    name: 'William',
    age: '68',
    sex: 'Male',
    ethnicity: 'White',
    size: 'L',
    height: "6'0\"",
    weight: '195 lbs',
    build: 'broad',
    facialFeatures: 'strong jaw, trimmed gray beard, wise expression',
    hairStyle: 'swept back',
    hairColor: 'silver gray',
    eyeColor: 'hazel',
    skinTone: 'weathered fair',
    fullDescription: 'Stately 68-year-old gentleman with silver gray hair swept back elegantly. His trimmed gray beard frames a strong jaw, and hazel eyes reflect years of experience.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-black-m-01',
    name: 'James',
    age: '65',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'M',
    height: "5'11\"",
    weight: '180 lbs',
    build: 'athletic',
    facialFeatures: 'distinguished gray beard, warm smile, dignified presence',
    hairStyle: 'short gray',
    hairColor: 'gray',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Distinguished 65-year-old man with a warm, welcoming presence. His short gray hair and neatly trimmed gray beard frame deep brown eyes that radiate kindness and wisdom.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-black-l-01',
    name: 'Charles',
    age: '70',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'L',
    height: "6'1\"",
    weight: '200 lbs',
    build: 'sturdy',
    facialFeatures: 'dignified expression, salt and pepper beard, gentle eyes',
    hairStyle: 'close cropped gray',
    hairColor: 'salt and pepper',
    eyeColor: 'brown',
    skinTone: 'deep brown',
    fullDescription: 'Commanding yet gentle 70-year-old man with close-cropped salt and pepper hair. His dignified bearing and kind brown eyes convey a lifetime of experience and wisdom.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-hispanic-m-01',
    name: 'Miguel',
    age: '63',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'9\"",
    weight: '170 lbs',
    build: 'average',
    facialFeatures: 'warm smile, distinguished mustache, expressive eyes',
    hairStyle: 'short wavy',
    hairColor: 'salt and pepper',
    eyeColor: 'brown',
    skinTone: 'warm olive',
    fullDescription: 'Charismatic 63-year-old man with warm olive skin and a genuine smile. His distinguished salt and pepper hair and neatly trimmed mustache give him a timeless elegance.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-asian-m-01',
    name: 'Hiroshi',
    age: '67',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'M',
    height: "5'7\"",
    weight: '155 lbs',
    build: 'lean',
    facialFeatures: 'thoughtful expression, minimal wrinkles, kind eyes',
    hairStyle: 'short neat',
    hairColor: 'silver gray',
    eyeColor: 'dark brown',
    skinTone: 'light golden',
    fullDescription: 'Refined 67-year-old man with silver gray hair neatly styled. His thoughtful expression and kind dark eyes reflect a contemplative nature and inner calm.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-indian-m-01',
    name: 'Raj',
    age: '64',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'M',
    height: "5'8\"",
    weight: '165 lbs',
    build: 'average',
    facialFeatures: 'distinguished gray temples, warm expression, wise eyes',
    hairStyle: 'short with gray temples',
    hairColor: 'salt and pepper',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Dignified 64-year-old man with distinguished gray temples framing his warm brown complexion. His wise dark eyes and gentle smile convey approachability and experience.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-middleeastern-m-01',
    name: 'Ahmed',
    age: '66',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'10\"",
    weight: '175 lbs',
    build: 'average',
    facialFeatures: 'distinguished gray beard, warm eyes, dignified presence',
    hairStyle: 'short neat',
    hairColor: 'gray',
    eyeColor: 'brown',
    skinTone: 'olive',
    fullDescription: 'Distinguished 66-year-old man with a neatly trimmed gray beard and warm brown eyes. His dignified presence and gentle demeanor inspire trust and respect.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-white-m-01',
    name: 'Margaret',
    age: '62',
    sex: 'Female',
    ethnicity: 'White',
    size: 'M',
    height: "5'5\"",
    weight: '145 lbs',
    build: 'average',
    facialFeatures: 'elegant features, warm smile, graceful aging',
    hairStyle: 'shoulder-length layered',
    hairColor: 'silver blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Elegant 62-year-old woman with silver blonde hair styled in graceful layers. Her blue eyes sparkle with warmth, and her natural grace reflects a lifetime of confidence.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-white-l-01',
    name: 'Patricia',
    age: '69',
    sex: 'Female',
    ethnicity: 'White',
    size: 'L',
    height: "5'6\"",
    weight: '160 lbs',
    build: 'full figured',
    facialFeatures: 'kind expression, natural beauty, gentle smile',
    hairStyle: 'short styled',
    hairColor: 'pure white',
    eyeColor: 'green',
    skinTone: 'fair with natural aging',
    fullDescription: 'Gracious 69-year-old woman with pure white hair elegantly styled. Her green eyes convey kindness and her gentle smile puts everyone at ease.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-black-m-01',
    name: 'Dorothy',
    age: '64',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'M',
    height: "5'6\"",
    weight: '150 lbs',
    build: 'average',
    facialFeatures: 'radiant smile, high cheekbones, graceful presence',
    hairStyle: 'natural gray curls',
    hairColor: 'silver gray',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Radiant 64-year-old woman with beautiful natural gray curls. Her high cheekbones and warm dark brown eyes reflect inner strength and timeless beauty.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-black-l-01',
    name: 'Eleanor',
    age: '71',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'L',
    height: "5'7\"",
    weight: '165 lbs',
    build: 'full figured',
    facialFeatures: 'regal bearing, warm expression, dignified beauty',
    hairStyle: 'short gray natural',
    hairColor: 'gray',
    eyeColor: 'brown',
    skinTone: 'deep brown',
    fullDescription: 'Regal 71-year-old woman with short natural gray hair and a commanding yet warm presence. Her dignified beauty and brown eyes radiate wisdom and grace.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-hispanic-m-01',
    name: 'Rosa',
    age: '63',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'4\"",
    weight: '140 lbs',
    build: 'petite',
    facialFeatures: 'warm smile, expressive eyes, natural elegance',
    hairStyle: 'medium length wavy',
    hairColor: 'salt and pepper',
    eyeColor: 'brown',
    skinTone: 'warm olive',
    fullDescription: 'Warm 63-year-old woman with salt and pepper hair in gentle waves. Her expressive brown eyes and genuine smile reflect a nurturing spirit and timeless grace.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-asian-m-01',
    name: 'Yuki',
    age: '65',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'M',
    height: "5'3\"",
    weight: '125 lbs',
    build: 'slender',
    facialFeatures: 'serene expression, minimal wrinkles, elegant poise',
    hairStyle: 'bob cut',
    hairColor: 'salt and pepper',
    eyeColor: 'dark brown',
    skinTone: 'light golden',
    fullDescription: 'Serene 65-year-old woman with an elegant salt and pepper bob cut. Her minimal wrinkles and graceful poise speak to a life of inner peace and refined taste.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-indian-m-01',
    name: 'Lakshmi',
    age: '66',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'M',
    height: "5'4\"",
    weight: '145 lbs',
    build: 'average',
    facialFeatures: 'graceful features, warm smile, gentle eyes',
    hairStyle: 'long with gray streaks',
    hairColor: 'black with silver streaks',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Graceful 66-year-old woman with long hair featuring distinguished silver streaks. Her warm smile and gentle dark eyes convey a lifetime of wisdom and warmth.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-middleeastern-m-01',
    name: 'Fatima',
    age: '64',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'5\"",
    weight: '150 lbs',
    build: 'average',
    facialFeatures: 'elegant features, warm expression, dignified beauty',
    hairStyle: 'medium length styled',
    hairColor: 'salt and pepper',
    eyeColor: 'brown',
    skinTone: 'olive',
    fullDescription: 'Elegant 64-year-old woman with salt and pepper hair styled gracefully. Her warm brown eyes and dignified presence reflect a life of experience and inner strength.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-white-xl-01',
    name: 'George',
    age: '72',
    sex: 'Male',
    ethnicity: 'White',
    size: 'XL',
    height: "6'2\"",
    weight: '220 lbs',
    build: 'large frame',
    facialFeatures: 'full gray beard, weathered features, kind eyes',
    hairStyle: 'receding gray',
    hairColor: 'white',
    eyeColor: 'blue',
    skinTone: 'fair weathered',
    fullDescription: 'Imposing yet friendly 72-year-old man with a full gray beard and kind blue eyes. His large frame and white hair give him a grandfather-like warmth.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-white-s-01',
    name: 'Helen',
    age: '67',
    sex: 'Female',
    ethnicity: 'White',
    size: 'S',
    height: "5'2\"",
    weight: '120 lbs',
    build: 'petite',
    facialFeatures: 'delicate features, bright eyes, warm smile',
    hairStyle: 'short pixie',
    hairColor: 'pure white',
    eyeColor: 'gray blue',
    skinTone: 'fair',
    fullDescription: 'Petite 67-year-old woman with a chic white pixie cut. Her bright gray-blue eyes and warm smile convey energy and youthful spirit despite her years.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-male-black-xl-01',
    name: 'Henry',
    age: '68',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'XL',
    height: "6'3\"",
    weight: '230 lbs',
    build: 'large athletic',
    facialFeatures: 'commanding presence, gray goatee, wise expression',
    hairStyle: 'bald',
    hairColor: 'none',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Commanding 68-year-old man with a bald head and distinguished gray goatee. His large athletic frame and wise dark brown eyes convey strength and experience.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'senior-female-asian-s-01',
    name: 'Keiko',
    age: '70',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'S',
    height: "5'1\"",
    weight: '110 lbs',
    build: 'petite slender',
    facialFeatures: 'serene beauty, gentle smile, wise eyes',
    hairStyle: 'short layered',
    hairColor: 'silver white',
    eyeColor: 'dark brown',
    skinTone: 'light golden',
    fullDescription: 'Serene 70-year-old woman with beautiful silver white hair in short layers. Her gentle smile and wise dark eyes reflect decades of grace and inner peace.',
    version: '1.0',
    createdDate: '2024-01-15'
  }
];
