import { UnifiedPersona } from '@shared/mockupTypes';

export const TODDLER_PERSONAS: UnifiedPersona[] = [
  {
    id: 'toddler-male-white-xs-01',
    name: 'Liam',
    age: '2',
    sex: 'Male',
    ethnicity: 'White',
    size: 'XS',
    height: "34\"",
    weight: '28 lbs',
    build: 'active toddler',
    facialFeatures: 'curious expression, rosy cheeks',
    hairStyle: 'tousled',
    hairColor: 'light brown',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Energetic 2-year-old boy with a curious expression and rosy cheeks. Tousled light brown hair and bright blue eyes full of wonder.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-white-xs-01_liam_headshot.png'
  },
  {
    id: 'toddler-male-black-xs-01',
    name: 'Miles',
    age: '3',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'XS',
    height: "37\"",
    weight: '32 lbs',
    build: 'sturdy toddler',
    facialFeatures: 'bright smile, expressive eyes',
    hairStyle: 'short curly',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Cheerful 3-year-old boy with a bright smile and expressive eyes. Short curly black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-black-xs-01_miles_headshot.png'
  },
  {
    id: 'toddler-male-hispanic-xs-01',
    name: 'Diego',
    age: '2',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'XS',
    height: "35\"",
    weight: '29 lbs',
    build: 'active toddler',
    facialFeatures: 'playful expression, dimples',
    hairStyle: 'wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm tan',
    fullDescription: 'Playful 2-year-old boy with a mischievous smile and cute dimples. Wavy dark brown hair and sparkling brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-hispanic-xs-01_diego_headshot.png'
  },
  {
    id: 'toddler-male-asian-xs-01',
    name: 'Ethan',
    age: '3',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'XS',
    height: "36\"",
    weight: '30 lbs',
    build: 'lean toddler',
    facialFeatures: 'thoughtful look, round face',
    hairStyle: 'straight bowl cut',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Thoughtful 3-year-old boy with a round face and inquisitive expression. Straight black hair in a neat bowl cut and observant dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-asian-xs-01_ethan_headshot.png'
  },
  {
    id: 'toddler-male-indian-xs-01',
    name: 'Dev',
    age: '2',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'XS',
    height: "34\"",
    weight: '28 lbs',
    build: 'healthy toddler',
    facialFeatures: 'big eyes, sweet smile',
    hairStyle: 'thick wavy',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Sweet 2-year-old boy with big expressive eyes and an endearing smile. Thick wavy black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-indian-xs-01_dev_headshot.png'
  },
  {
    id: 'toddler-male-southeast-asian-xs-01',
    name: 'Tan',
    age: '3',
    sex: 'Male',
    ethnicity: 'Southeast Asian',
    size: 'XS',
    height: "35\"",
    weight: '29 lbs',
    build: 'active toddler',
    facialFeatures: 'happy expression, chubby cheeks',
    hairStyle: 'straight short',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'tan',
    fullDescription: 'Happy 3-year-old boy with chubby cheeks and a joyful demeanor. Short straight black hair and bright dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-southeast-asian-xs-01_tan_headshot.png'
  },
  {
    id: 'toddler-male-middle-eastern-xs-01',
    name: 'Sami',
    age: '2',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'XS',
    height: "34\"",
    weight: '28 lbs',
    build: 'healthy toddler',
    facialFeatures: 'large eyes, long lashes',
    hairStyle: 'thick curly',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Adorable 2-year-old boy with large expressive eyes and striking long lashes. Thick curly black hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-middle-eastern-xs-01_sami_headshot.png'
  },
  {
    id: 'toddler-male-indigenous-xs-01',
    name: 'Bear',
    age: '3',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'XS',
    height: "36\"",
    weight: '31 lbs',
    build: 'sturdy toddler',
    facialFeatures: 'bright smile, round face',
    hairStyle: 'straight thick',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Cheerful 3-year-old boy with a bright smile and round face. Thick straight black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-indigenous-xs-01_bear_headshot.png'
  },
  {
    id: 'toddler-male-diverse-xs-01',
    name: 'Kai',
    age: '2',
    sex: 'Male',
    ethnicity: 'Diverse',
    size: 'XS',
    height: "35\"",
    weight: '29 lbs',
    build: 'active toddler',
    facialFeatures: 'mixed features, friendly expression',
    hairStyle: 'loose curls',
    hairColor: 'light brown',
    eyeColor: 'hazel',
    skinTone: 'golden brown',
    fullDescription: 'Friendly 2-year-old boy with beautifully blended features. Loose curly light brown hair and striking hazel eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-male-diverse-xs-01_kai_headshot.png'
  },
  {
    id: 'toddler-female-white-xs-01',
    name: 'Ava',
    age: '2',
    sex: 'Female',
    ethnicity: 'White',
    size: 'XS',
    height: "33\"",
    weight: '26 lbs',
    build: 'petite toddler',
    facialFeatures: 'sweet expression, button nose',
    hairStyle: 'pigtails',
    hairColor: 'blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Sweet 2-year-old girl with an adorable button nose. Blonde hair in cute pigtails and bright blue eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-white-xs-01_ava_headshot.png'
  },
  {
    id: 'toddler-female-black-xs-01',
    name: 'Nia',
    age: '3',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'XS',
    height: "36\"",
    weight: '30 lbs',
    build: 'healthy toddler',
    facialFeatures: 'joyful smile, expressive eyes',
    hairStyle: 'puffs',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'deep brown',
    fullDescription: 'Joyful 3-year-old girl with an infectious smile. Beautiful black hair styled in adorable puffs and sparkling dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-black-xs-01_nia_headshot.png'
  },
  {
    id: 'toddler-female-hispanic-xs-01',
    name: 'Isabella',
    age: '2',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'XS',
    height: "34\"",
    weight: '27 lbs',
    build: 'active toddler',
    facialFeatures: 'rosy cheeks, dimples',
    hairStyle: 'wavy loose',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'olive',
    fullDescription: 'Adorable 2-year-old girl with rosy cheeks and sweet dimples. Wavy dark brown hair and warm brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-hispanic-xs-01_isabella_headshot.png'
  },
  {
    id: 'toddler-female-asian-xs-01',
    name: 'Lily',
    age: '3',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'XS',
    height: "35\"",
    weight: '28 lbs',
    build: 'petite toddler',
    facialFeatures: 'delicate features, curious look',
    hairStyle: 'straight with bangs',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Curious 3-year-old girl with delicate features. Straight black hair with cute bangs and observant dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-asian-xs-01_lily_headshot.png'
  },
  {
    id: 'toddler-female-indian-xs-01',
    name: 'Priya',
    age: '2',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'XS',
    height: "33\"",
    weight: '26 lbs',
    build: 'healthy toddler',
    facialFeatures: 'big eyes, sweet smile',
    hairStyle: 'thick braids',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Sweet 2-year-old girl with big expressive eyes. Thick black hair in little braids and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-indian-xs-01_priya_headshot.png'
  },
  {
    id: 'toddler-female-southeast-asian-xs-01',
    name: 'Mai',
    age: '3',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'XS',
    height: "34\"",
    weight: '27 lbs',
    build: 'petite toddler',
    facialFeatures: 'gentle expression, round cheeks',
    hairStyle: 'short bob',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light tan',
    fullDescription: 'Gentle 3-year-old girl with round cheeks and a calm demeanor. Short black bob haircut and attentive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-southeast-asian-xs-01_mai_headshot.png'
  },
  {
    id: 'toddler-female-middle-eastern-xs-01',
    name: 'Yasmin',
    age: '2',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'XS',
    height: "33\"",
    weight: '26 lbs',
    build: 'healthy toddler',
    facialFeatures: 'large eyes, long lashes',
    hairStyle: 'curly loose',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'olive',
    fullDescription: 'Beautiful 2-year-old girl with large eyes and striking long lashes. Loose curly dark brown hair and deep brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-middle-eastern-xs-01_yasmin_headshot.png'
  },
  {
    id: 'toddler-female-indigenous-xs-01',
    name: 'Willow',
    age: '3',
    sex: 'Female',
    ethnicity: 'Indigenous',
    size: 'XS',
    height: "35\"",
    weight: '29 lbs',
    build: 'healthy toddler',
    facialFeatures: 'bright smile, round face',
    hairStyle: 'long straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Happy 3-year-old girl with a bright smile and round face. Long straight black hair and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-indigenous-xs-01_willow_headshot.png'
  },
  {
    id: 'toddler-female-diverse-xs-01',
    name: 'Luna',
    age: '2',
    sex: 'Female',
    ethnicity: 'Diverse',
    size: 'XS',
    height: "34\"",
    weight: '27 lbs',
    build: 'active toddler',
    facialFeatures: 'mixed features, radiant smile',
    hairStyle: 'bouncy curls',
    hairColor: 'auburn',
    eyeColor: 'green',
    skinTone: 'caramel',
    fullDescription: 'Radiant 2-year-old girl with beautifully blended features. Bouncy auburn curls and striking green eyes.',
    version: '1.0',
    createdDate: '2024-12-28',
    headshotUrl: 'attached_assets/personas/toddler-female-diverse-xs-01_luna_headshot.png'
  }
];
