/**
 * ============================================================================
 * ADULT PERSONAS - MISSING 72 PERSONAS
 * Age Range: 25-45 years
 * ============================================================================
 */

export const missingAdultPersonas = [
  // ============================================================================
  // WHITE FEMALE - Missing: XS, S, L, 2XL (4)
  // ============================================================================
  {
    id: "WHT_AD_F_XS_001",
    name: "Emily",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "White",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Defined features, bright blue eyes, mature elegance, fine lines showing wisdom",
    hairStyle: "Styled professionally",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Emily is a 28-year-old adult female of White heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows defined features, bright blue eyes, and mature elegance. She has styled professionally light brown with subtle gray hair and blue eyes. Her fair with warm undertones skin has a healthy mature glow. Emily carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_F_S_001",
    name: "Rachel",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "White",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Defined features, bright blue eyes, mature elegance, subtle laugh lines",
    hairStyle: "Styled professionally",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Rachel is a 31-year-old adult female of White heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with toned proportions. Her face shows defined features, bright blue eyes, and mature elegance. She has styled professionally light brown with subtle gray hair and blue eyes. Her fair with warm undertones skin has a healthy mature glow. Rachel carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_F_L_001",
    name: "Katherine",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "White",
    size: "L",
    height: "173cm (5'8\")",
    weight: "75kg (165lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Defined features, bright blue eyes, mature elegance, confident expression",
    hairStyle: "Styled professionally",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Katherine is a 37-year-old adult female of White heritage, standing 173cm (5'8\") tall and weighing approximately 75kg (165lbs). She has a sturdy athletic frame with strong proportions. Her face shows defined features, bright blue eyes, and mature elegance. She has styled professionally light brown with subtle gray hair and blue eyes. Her fair with warm undertones skin has a healthy mature glow. Katherine carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_F_2XL_001",
    name: "Margaret",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "White",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Defined features, bright blue eyes, mature elegance, warm expression",
    hairStyle: "Styled professionally",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Margaret is a 43-year-old adult female of White heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows defined features, bright blue eyes, and mature elegance. She has styled professionally light brown with subtle gray hair and blue eyes. Her fair with warm undertones skin has a healthy mature glow. Margaret carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // WHITE MALE - Missing: XS, S, XL, 2XL (4)
  // ============================================================================
  {
    id: "WHT_AD_M_XS_001",
    name: "Brian",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "White",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong jawline, defined features, mature presence, light stubble",
    hairStyle: "Short professional cut",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Brian is a 28-year-old adult male of White heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows strong jawline, defined features, and mature presence. He has short professional cut light brown with subtle gray hair and blue eyes. His fair with warm undertones skin has a healthy mature glow. Brian carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_M_S_001",
    name: "Kevin",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "White",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong jawline, defined features, mature presence, clean shaven",
    hairStyle: "Short professional cut",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Kevin is a 31-year-old adult male of White heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows strong jawline, defined features, and mature presence. He has short professional cut light brown with subtle gray hair and blue eyes. His fair with warm undertones skin has a healthy mature glow. Kevin carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_M_XL_001",
    name: "Patrick",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "White",
    size: "XL",
    height: "185cm (6'1\")",
    weight: "102kg (225lbs)",
    build: "Large muscular frame",
    facialFeatures: "Strong jawline, defined features, mature presence, full beard",
    hairStyle: "Short professional cut",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Patrick is a 40-year-old adult male of White heritage, standing 185cm (6'1\") tall and weighing approximately 102kg (225lbs). He has a large muscular frame with powerful proportions. His face shows strong jawline, defined features, and mature presence. He has short professional cut light brown with subtle gray hair and blue eyes. His fair with warm undertones skin has a healthy mature glow. Patrick carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_AD_M_2XL_001",
    name: "Donald",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "White",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Strong jawline, defined features, mature presence, distinguished look",
    hairStyle: "Short professional cut",
    hairColor: "Light brown with subtle gray",
    eyeColor: "Blue",
    skinTone: "Fair with warm undertones",
    fullDescription: "Donald is a 43-year-old adult male of White heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows strong jawline, defined features, and mature presence. He has short professional cut light brown with subtle gray hair and blue eyes. His fair with warm undertones skin has a healthy mature glow. Donald carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK FEMALE - Missing: XS, S, L, 2XL (4)
  // ============================================================================
  {
    id: "BLK_AD_F_XS_001",
    name: "Aisha",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Black",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Full lips, high cheekbones, radiant skin, expressive dark eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Aisha is a 28-year-old adult female of Black heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows full lips, high cheekbones, and radiant skin. She has natural curls styled black hair and dark brown eyes. Her rich deep brown skin has a healthy mature glow. Aisha carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_F_S_001",
    name: "Jasmine",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Black",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Full lips, high cheekbones, radiant skin, warm smile",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Jasmine is a 31-year-old adult female of Black heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with toned proportions. Her face shows full lips, high cheekbones, and radiant skin. She has natural curls styled black hair and dark brown eyes. Her rich deep brown skin has a healthy mature glow. Jasmine carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_F_L_001",
    name: "Denise",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Black",
    size: "L",
    height: "173cm (5'8\")",
    weight: "75kg (165lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Full lips, high cheekbones, radiant skin, confident expression",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Denise is a 37-year-old adult female of Black heritage, standing 173cm (5'8\") tall and weighing approximately 75kg (165lbs). She has a sturdy athletic frame with strong proportions. Her face shows full lips, high cheekbones, and radiant skin. She has natural curls styled black hair and dark brown eyes. Her rich deep brown skin has a healthy mature glow. Denise carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_F_2XL_001",
    name: "Patricia",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Black",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Full lips, high cheekbones, radiant skin, regal presence",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Patricia is a 43-year-old adult female of Black heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows full lips, high cheekbones, and radiant skin. She has natural curls styled black hair and dark brown eyes. Her rich deep brown skin has a healthy mature glow. Patricia carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK MALE - Missing: XS, S, M, 2XL (4)
  // ============================================================================
  {
    id: "BLK_AD_M_XS_001",
    name: "Dwayne",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Black",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong features, broad nose, confident expression, clean shaven",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Dwayne is a 28-year-old adult male of Black heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows strong features, broad nose, and confident expression. He has short fade cut black hair and dark brown eyes. His rich deep brown skin has a healthy mature glow. Dwayne carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_M_S_001",
    name: "Andre",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Black",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong features, broad nose, confident expression, goatee",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Andre is a 31-year-old adult male of Black heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows strong features, broad nose, and confident expression. He has short fade cut black hair and dark brown eyes. His rich deep brown skin has a healthy mature glow. Andre carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_M_M_001",
    name: "Terrance",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Black",
    size: "M",
    height: "178cm (5'10\")",
    weight: "79kg (174lbs)",
    build: "Average athletic frame",
    facialFeatures: "Strong features, broad nose, confident expression, trimmed beard",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Terrance is a 34-year-old adult male of Black heritage, standing 178cm (5'10\") tall and weighing approximately 79kg (174lbs). He has an average athletic frame with balanced proportions. His face shows strong features, broad nose, and confident expression. He has short fade cut black hair and dark brown eyes. His rich deep brown skin has a healthy mature glow. Terrance carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_AD_M_2XL_001",
    name: "Reginald",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Black",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Strong features, broad nose, confident expression, full beard",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich deep brown",
    fullDescription: "Reginald is a 43-year-old adult male of Black heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with powerful proportions. His face shows strong features, broad nose, and confident expression. He has short fade cut black hair and dark brown eyes. His rich deep brown skin has a healthy mature glow. Reginald carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC FEMALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "HSP_AD_F_XS_001",
    name: "Lucia",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Warm expressive eyes, defined cheekbones, natural beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Lucia is a 28-year-old adult female of Hispanic heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows warm expressive eyes, defined cheekbones, and natural beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive skin has a healthy mature glow. Lucia carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_F_S_001",
    name: "Isabella",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Warm expressive eyes, defined cheekbones, radiant smile",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Isabella is a 31-year-old adult female of Hispanic heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with graceful proportions. Her face shows warm expressive eyes, defined cheekbones, and radiant smile. She has long flowing style dark brown hair and warm brown eyes. Her warm olive skin has a healthy mature glow. Isabella carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_F_M_001",
    name: "Gabriela",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "M",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Average athletic frame",
    facialFeatures: "Warm expressive eyes, defined cheekbones, confident expression",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Gabriela is a 34-year-old adult female of Hispanic heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). She has an average athletic frame with balanced proportions. Her face shows warm expressive eyes, defined cheekbones, and confident expression. She has long flowing style dark brown hair and warm brown eyes. Her warm olive skin has a healthy mature glow. Gabriela carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_F_XL_001",
    name: "Marisol",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XL",
    height: "175cm (5'9\")",
    weight: "85kg (187lbs)",
    build: "Large athletic frame",
    facialFeatures: "Warm expressive eyes, defined cheekbones, warm presence",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Marisol is a 40-year-old adult female of Hispanic heritage, standing 175cm (5'9\") tall and weighing approximately 85kg (187lbs). She has a large athletic frame with strong proportions. Her face shows warm expressive eyes, defined cheekbones, and warm presence. She has long flowing style dark brown hair and warm brown eyes. Her warm olive skin has a healthy mature glow. Marisol carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_F_2XL_001",
    name: "Esperanza",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Warm expressive eyes, defined cheekbones, maternal warmth",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Esperanza is a 43-year-old adult female of Hispanic heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows warm expressive eyes, defined cheekbones, and maternal warmth. She has long flowing style dark brown hair and warm brown eyes. Her warm olive skin has a healthy mature glow. Esperanza carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC MALE - Missing: XS, S, M, L, 2XL (5)
  // ============================================================================
  {
    id: "HSP_AD_M_XS_001",
    name: "Diego",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong features, warm expression, defined jaw, clean shaven",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Diego is a 28-year-old adult male of Hispanic heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive skin has a healthy mature glow. Diego carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_M_S_001",
    name: "Rafael",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong features, warm expression, defined jaw, light stubble",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Rafael is a 31-year-old adult male of Hispanic heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive skin has a healthy mature glow. Rafael carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_M_M_001",
    name: "Javier",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "M",
    height: "178cm (5'10\")",
    weight: "79kg (174lbs)",
    build: "Average athletic frame",
    facialFeatures: "Strong features, warm expression, defined jaw, trimmed mustache",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Javier is a 34-year-old adult male of Hispanic heritage, standing 178cm (5'10\") tall and weighing approximately 79kg (174lbs). He has an average athletic frame with balanced proportions. His face shows strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive skin has a healthy mature glow. Javier carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_M_L_001",
    name: "Eduardo",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "L",
    height: "183cm (6'0\")",
    weight: "90kg (198lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Strong features, warm expression, defined jaw, full beard",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Eduardo is a 37-year-old adult male of Hispanic heritage, standing 183cm (6'0\") tall and weighing approximately 90kg (198lbs). He has a sturdy muscular frame with strong proportions. His face shows strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive skin has a healthy mature glow. Eduardo carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_AD_M_2XL_001",
    name: "Fernando",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Strong features, warm expression, defined jaw, distinguished look",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive",
    fullDescription: "Fernando is a 43-year-old adult male of Hispanic heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive skin has a healthy mature glow. Fernando carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN FEMALE - Missing: XS, S, L, 2XL (4)
  // ============================================================================
  {
    id: "ASN_AD_F_XS_001",
    name: "Yuki",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Asian",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Delicate features, almond eyes, graceful appearance, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Yuki is a 28-year-old adult female of Asian heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows delicate features, almond eyes, and graceful appearance. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin has a healthy mature glow. Yuki carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_F_S_001",
    name: "Mei Lin",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Asian",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Delicate features, almond eyes, graceful appearance, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Mei Lin is a 31-year-old adult female of Asian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with elegant proportions. Her face shows delicate features, almond eyes, and graceful appearance. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin has a healthy mature glow. Mei Lin carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_F_L_001",
    name: "Sakura",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Asian",
    size: "L",
    height: "173cm (5'8\")",
    weight: "75kg (165lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Delicate features, almond eyes, graceful appearance, confident expression",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Sakura is a 37-year-old adult female of Asian heritage, standing 173cm (5'8\") tall and weighing approximately 75kg (165lbs). She has a sturdy athletic frame with strong proportions. Her face shows delicate features, almond eyes, and graceful appearance. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin has a healthy mature glow. Sakura carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_F_2XL_001",
    name: "Kimiko",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Asian",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Delicate features, almond eyes, graceful appearance, serene expression",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Kimiko is a 43-year-old adult female of Asian heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows delicate features, almond eyes, and graceful appearance. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin has a healthy mature glow. Kimiko carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN MALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "ASN_AD_M_XS_001",
    name: "Kenji",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Asian",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Clean features, almond eyes, composed expression, clean shaven",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Kenji is a 28-year-old adult male of Asian heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows clean features, almond eyes, and composed expression. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin has a healthy mature glow. Kenji carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_M_S_001",
    name: "Hiroshi",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Asian",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Clean features, almond eyes, composed expression, light stubble",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Hiroshi is a 31-year-old adult male of Asian heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows clean features, almond eyes, and composed expression. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin has a healthy mature glow. Hiroshi carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_M_M_001",
    name: "Takeshi",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Asian",
    size: "M",
    height: "178cm (5'10\")",
    weight: "79kg (174lbs)",
    build: "Average athletic frame",
    facialFeatures: "Clean features, almond eyes, composed expression, professional look",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Takeshi is a 34-year-old adult male of Asian heritage, standing 178cm (5'10\") tall and weighing approximately 79kg (174lbs). He has an average athletic frame with balanced proportions. His face shows clean features, almond eyes, and composed expression. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin has a healthy mature glow. Takeshi carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_M_XL_001",
    name: "Daiki",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Asian",
    size: "XL",
    height: "185cm (6'1\")",
    weight: "102kg (225lbs)",
    build: "Large muscular frame",
    facialFeatures: "Clean features, almond eyes, composed expression, strong presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Daiki is a 40-year-old adult male of Asian heritage, standing 185cm (6'1\") tall and weighing approximately 102kg (225lbs). He has a large muscular frame with powerful proportions. His face shows clean features, almond eyes, and composed expression. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin has a healthy mature glow. Daiki carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_AD_M_2XL_001",
    name: "Masaru",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Asian",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Clean features, almond eyes, composed expression, distinguished presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Masaru is a 43-year-old adult male of Asian heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows clean features, almond eyes, and composed expression. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin has a healthy mature glow. Masaru carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN FEMALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "IND_AD_F_XS_001",
    name: "Priya",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indian",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Expressive dark eyes, elegant bone structure, warm glow",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Priya is a 28-year-old adult female of Indian heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows expressive dark eyes, elegant bone structure, and warm glow. She has long flowing style black hair and dark brown eyes. Her warm brown skin has a healthy mature glow. Priya carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_F_S_001",
    name: "Ananya",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indian",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Expressive dark eyes, elegant bone structure, graceful smile",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Ananya is a 31-year-old adult female of Indian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with elegant proportions. Her face shows expressive dark eyes, elegant bone structure, and graceful smile. She has long flowing style black hair and dark brown eyes. Her warm brown skin has a healthy mature glow. Ananya carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_F_M_001",
    name: "Divya",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indian",
    size: "M",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Average athletic frame",
    facialFeatures: "Expressive dark eyes, elegant bone structure, confident expression",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Divya is a 34-year-old adult female of Indian heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). She has an average athletic frame with balanced proportions. Her face shows expressive dark eyes, elegant bone structure, and confident expression. She has long flowing style black hair and dark brown eyes. Her warm brown skin has a healthy mature glow. Divya carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_F_XL_001",
    name: "Lakshmi",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indian",
    size: "XL",
    height: "175cm (5'9\")",
    weight: "85kg (187lbs)",
    build: "Large athletic frame",
    facialFeatures: "Expressive dark eyes, elegant bone structure, regal presence",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Lakshmi is a 40-year-old adult female of Indian heritage, standing 175cm (5'9\") tall and weighing approximately 85kg (187lbs). She has a large athletic frame with strong proportions. Her face shows expressive dark eyes, elegant bone structure, and regal presence. She has long flowing style black hair and dark brown eyes. Her warm brown skin has a healthy mature glow. Lakshmi carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_F_2XL_001",
    name: "Sunita",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indian",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Expressive dark eyes, elegant bone structure, maternal warmth",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Sunita is a 43-year-old adult female of Indian heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows expressive dark eyes, elegant bone structure, and maternal warmth. She has long flowing style black hair and dark brown eyes. Her warm brown skin has a healthy mature glow. Sunita carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN MALE - Missing: XS, S, XL, 2XL (4)
  // ============================================================================
  {
    id: "IND_AD_M_XS_001",
    name: "Raj",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indian",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong features, expressive eyes, dignified presence, clean shaven",
    hairStyle: "Short professional cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Raj is a 28-year-old adult male of Indian heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows strong features, expressive eyes, and dignified presence. He has short professional cut black hair and dark brown eyes. His warm brown skin has a healthy mature glow. Raj carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_M_S_001",
    name: "Amit",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indian",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong features, expressive eyes, dignified presence, light stubble",
    hairStyle: "Short professional cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Amit is a 31-year-old adult male of Indian heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows strong features, expressive eyes, and dignified presence. He has short professional cut black hair and dark brown eyes. His warm brown skin has a healthy mature glow. Amit carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_M_XL_001",
    name: "Deepak",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indian",
    size: "XL",
    height: "185cm (6'1\")",
    weight: "102kg (225lbs)",
    build: "Large muscular frame",
    facialFeatures: "Strong features, expressive eyes, dignified presence, full beard",
    hairStyle: "Short professional cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Deepak is a 40-year-old adult male of Indian heritage, standing 185cm (6'1\") tall and weighing approximately 102kg (225lbs). He has a large muscular frame with powerful proportions. His face shows strong features, expressive eyes, and dignified presence. He has short professional cut black hair and dark brown eyes. His warm brown skin has a healthy mature glow. Deepak carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_AD_M_2XL_001",
    name: "Suresh",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indian",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Strong features, expressive eyes, dignified presence, distinguished look",
    hairStyle: "Short professional cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown",
    fullDescription: "Suresh is a 43-year-old adult male of Indian heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows strong features, expressive eyes, and dignified presence. He has short professional cut black hair and dark brown eyes. His warm brown skin has a healthy mature glow. Suresh carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN FEMALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "SEA_AD_F_XS_001",
    name: "Linh",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Soft features, warm eyes, gentle expression",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Linh is a 28-year-old adult female of Southeast Asian heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows soft features, warm eyes, and gentle expression. She has long straight style black hair and dark brown eyes. Her light tan with golden undertones skin has a healthy mature glow. Linh carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_F_S_001",
    name: "Mai",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Soft features, warm eyes, graceful smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Mai is a 31-year-old adult female of Southeast Asian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with elegant proportions. Her face shows soft features, warm eyes, and graceful smile. She has long straight style black hair and dark brown eyes. Her light tan with golden undertones skin has a healthy mature glow. Mai carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_F_M_001",
    name: "Nguyet",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "M",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Average athletic frame",
    facialFeatures: "Soft features, warm eyes, confident expression",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Nguyet is a 34-year-old adult female of Southeast Asian heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). She has an average athletic frame with balanced proportions. Her face shows soft features, warm eyes, and confident expression. She has long straight style black hair and dark brown eyes. Her light tan with golden undertones skin has a healthy mature glow. Nguyet carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_F_XL_001",
    name: "Lawan",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XL",
    height: "175cm (5'9\")",
    weight: "85kg (187lbs)",
    build: "Large athletic frame",
    facialFeatures: "Soft features, warm eyes, serene presence",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Lawan is a 40-year-old adult female of Southeast Asian heritage, standing 175cm (5'9\") tall and weighing approximately 85kg (187lbs). She has a large athletic frame with strong proportions. Her face shows soft features, warm eyes, and serene presence. She has long straight style black hair and dark brown eyes. Her light tan with golden undertones skin has a healthy mature glow. Lawan carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_F_2XL_001",
    name: "Sita",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "Soft features, warm eyes, maternal warmth",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Sita is a 43-year-old adult female of Southeast Asian heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows soft features, warm eyes, and maternal warmth. She has long straight style black hair and dark brown eyes. Her light tan with golden undertones skin has a healthy mature glow. Sita carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN MALE - Missing: XS, S, M, L, 2XL (5)
  // ============================================================================
  {
    id: "SEA_AD_M_XS_001",
    name: "Somchai",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Warm features, friendly eyes, approachable expression, clean shaven",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Somchai is a 28-year-old adult male of Southeast Asian heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with golden undertones skin has a healthy mature glow. Somchai carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_M_S_001",
    name: "Nguyen",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Warm features, friendly eyes, approachable expression, light stubble",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Nguyen is a 31-year-old adult male of Southeast Asian heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with golden undertones skin has a healthy mature glow. Nguyen carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_M_M_001",
    name: "Boun",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "M",
    height: "178cm (5'10\")",
    weight: "79kg (174lbs)",
    build: "Average athletic frame",
    facialFeatures: "Warm features, friendly eyes, approachable expression, professional look",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Boun is a 34-year-old adult male of Southeast Asian heritage, standing 178cm (5'10\") tall and weighing approximately 79kg (174lbs). He has an average athletic frame with balanced proportions. His face shows warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with golden undertones skin has a healthy mature glow. Boun carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_M_L_001",
    name: "Kiet",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "L",
    height: "183cm (6'0\")",
    weight: "90kg (198lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Warm features, friendly eyes, approachable expression, trimmed beard",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Kiet is a 37-year-old adult male of Southeast Asian heritage, standing 183cm (6'0\") tall and weighing approximately 90kg (198lbs). He has a sturdy muscular frame with strong proportions. His face shows warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with golden undertones skin has a healthy mature glow. Kiet carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_AD_M_2XL_001",
    name: "Phong",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Warm features, friendly eyes, approachable expression, distinguished look",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with golden undertones",
    fullDescription: "Phong is a 43-year-old adult male of Southeast Asian heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with golden undertones skin has a healthy mature glow. Phong carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN FEMALE - Missing: XS, S, M, XL (4)
  // ============================================================================
  {
    id: "MDE_AD_F_XS_001",
    name: "Fatima",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "Striking dark eyes, defined features, elegant bone structure",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Fatima is a 28-year-old adult female of Middle Eastern heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows striking dark eyes, defined features, and elegant bone structure. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm undertones skin has a healthy mature glow. Fatima carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_F_S_001",
    name: "Layla",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Striking dark eyes, defined features, graceful smile",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Layla is a 31-year-old adult female of Middle Eastern heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with elegant proportions. Her face shows striking dark eyes, defined features, and graceful smile. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm undertones skin has a healthy mature glow. Layla carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_F_M_001",
    name: "Zahra",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "M",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Average athletic frame",
    facialFeatures: "Striking dark eyes, defined features, confident expression",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Zahra is a 34-year-old adult female of Middle Eastern heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). She has an average athletic frame with balanced proportions. Her face shows striking dark eyes, defined features, and confident expression. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm undertones skin has a healthy mature glow. Zahra carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_F_XL_001",
    name: "Amira",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XL",
    height: "175cm (5'9\")",
    weight: "85kg (187lbs)",
    build: "Large athletic frame",
    facialFeatures: "Striking dark eyes, defined features, regal presence",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Amira is a 40-year-old adult female of Middle Eastern heritage, standing 175cm (5'9\") tall and weighing approximately 85kg (187lbs). She has a large athletic frame with strong proportions. Her face shows striking dark eyes, defined features, and regal presence. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm undertones skin has a healthy mature glow. Amira carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN MALE - Missing: XS, S, L, 2XL (4)
  // ============================================================================
  {
    id: "MDE_AD_M_XS_001",
    name: "Omar",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong defined features, dark expressive eyes, distinguished presence, clean shaven",
    hairStyle: "Short professional cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Omar is a 28-year-old adult male of Middle Eastern heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows strong defined features, dark expressive eyes, and distinguished presence. He has short professional cut dark brown to black hair and dark brown eyes. His olive with warm undertones skin has a healthy mature glow. Omar carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_M_S_001",
    name: "Khalid",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong defined features, dark expressive eyes, distinguished presence, light stubble",
    hairStyle: "Short professional cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Khalid is a 31-year-old adult male of Middle Eastern heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows strong defined features, dark expressive eyes, and distinguished presence. He has short professional cut dark brown to black hair and dark brown eyes. His olive with warm undertones skin has a healthy mature glow. Khalid carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_M_L_001",
    name: "Ahmed",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "L",
    height: "183cm (6'0\")",
    weight: "90kg (198lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Strong defined features, dark expressive eyes, distinguished presence, full beard",
    hairStyle: "Short professional cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Ahmed is a 37-year-old adult male of Middle Eastern heritage, standing 183cm (6'0\") tall and weighing approximately 90kg (198lbs). He has a sturdy muscular frame with strong proportions. His face shows strong defined features, dark expressive eyes, and distinguished presence. He has short professional cut dark brown to black hair and dark brown eyes. His olive with warm undertones skin has a healthy mature glow. Ahmed carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_AD_M_2XL_001",
    name: "Yusuf",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "Strong defined features, dark expressive eyes, distinguished presence, distinguished look",
    hairStyle: "Short professional cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm undertones",
    fullDescription: "Yusuf is a 43-year-old adult male of Middle Eastern heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows strong defined features, dark expressive eyes, and distinguished presence. He has short professional cut dark brown to black hair and dark brown eyes. His olive with warm undertones skin has a healthy mature glow. Yusuf carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS FEMALE - Missing: XS, S, M, L, 2XL (5)
  // ============================================================================
  {
    id: "IDG_AD_F_XS_001",
    name: "Kaya",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "XS",
    height: "157cm (5'2\")",
    weight: "50kg (110lbs)",
    build: "Petite slim frame",
    facialFeatures: "High cheekbones, strong features, natural dignity",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Kaya is a 28-year-old adult female of Indigenous heritage, standing 157cm (5'2\") tall and weighing approximately 50kg (110lbs). She has a petite slim frame with delicate proportions. Her face shows high cheekbones, strong features, and natural dignity. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin has a healthy mature glow. Kaya carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_F_S_001",
    name: "Aiyana",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "S",
    height: "163cm (5'4\")",
    weight: "57kg (125lbs)",
    build: "Slim athletic frame",
    facialFeatures: "High cheekbones, strong features, graceful presence",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Aiyana is a 31-year-old adult female of Indigenous heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (125lbs). She has a slim athletic frame with elegant proportions. Her face shows high cheekbones, strong features, and graceful presence. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin has a healthy mature glow. Aiyana carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_F_M_001",
    name: "Winona",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "M",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Average athletic frame",
    facialFeatures: "High cheekbones, strong features, confident expression",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Winona is a 34-year-old adult female of Indigenous heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). She has an average athletic frame with balanced proportions. Her face shows high cheekbones, strong features, and confident expression. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin has a healthy mature glow. Winona carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_F_L_001",
    name: "Chenoa",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "L",
    height: "173cm (5'8\")",
    weight: "75kg (165lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "High cheekbones, strong features, proud presence",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Chenoa is a 37-year-old adult female of Indigenous heritage, standing 173cm (5'8\") tall and weighing approximately 75kg (165lbs). She has a sturdy athletic frame with strong proportions. Her face shows high cheekbones, strong features, and proud presence. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin has a healthy mature glow. Chenoa carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_F_2XL_001",
    name: "Halona",
    age: "Adult",
    ageRange: "25-45",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "178cm (5'10\")",
    weight: "100kg (220lbs)",
    build: "Plus size frame",
    facialFeatures: "High cheekbones, strong features, maternal warmth",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Halona is a 43-year-old adult female of Indigenous heritage, standing 178cm (5'10\") tall and weighing approximately 100kg (220lbs). She has a plus size frame with full proportions. Her face shows high cheekbones, strong features, and maternal warmth. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin has a healthy mature glow. Halona carries herself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS MALE - Missing: XS, S, M, L, 2XL (5)
  // ============================================================================
  {
    id: "IDG_AD_M_XS_001",
    name: "Chayton",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "XS",
    height: "165cm (5'5\")",
    weight: "60kg (132lbs)",
    build: "Slim lean frame",
    facialFeatures: "High cheekbones, strong angular features, proud presence, clean shaven",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Chayton is a 28-year-old adult male of Indigenous heritage, standing 165cm (5'5\") tall and weighing approximately 60kg (132lbs). He has a slim lean frame with compact proportions. His face shows high cheekbones, strong angular features, and proud presence. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin has a healthy mature glow. Chayton carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_M_S_001",
    name: "Takoda",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "S",
    height: "170cm (5'7\")",
    weight: "68kg (150lbs)",
    build: "Slim athletic frame",
    facialFeatures: "High cheekbones, strong angular features, proud presence, light stubble",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Takoda is a 31-year-old adult male of Indigenous heritage, standing 170cm (5'7\") tall and weighing approximately 68kg (150lbs). He has a slim athletic frame with lean proportions. His face shows high cheekbones, strong angular features, and proud presence. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin has a healthy mature glow. Takoda carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_M_M_001",
    name: "Ahanu",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "M",
    height: "178cm (5'10\")",
    weight: "79kg (174lbs)",
    build: "Average athletic frame",
    facialFeatures: "High cheekbones, strong angular features, proud presence, professional look",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Ahanu is a 34-year-old adult male of Indigenous heritage, standing 178cm (5'10\") tall and weighing approximately 79kg (174lbs). He has an average athletic frame with balanced proportions. His face shows high cheekbones, strong angular features, and proud presence. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin has a healthy mature glow. Ahanu carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_M_L_001",
    name: "Koda",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "L",
    height: "183cm (6'0\")",
    weight: "90kg (198lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "High cheekbones, strong angular features, proud presence, warrior bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Koda is a 37-year-old adult male of Indigenous heritage, standing 183cm (6'0\") tall and weighing approximately 90kg (198lbs). He has a sturdy muscular frame with strong proportions. His face shows high cheekbones, strong angular features, and proud presence. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin has a healthy mature glow. Koda carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_AD_M_2XL_001",
    name: "Elan",
    age: "Adult",
    ageRange: "25-45",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "188cm (6'2\")",
    weight: "118kg (260lbs)",
    build: "Very large frame",
    facialFeatures: "High cheekbones, strong angular features, proud presence, distinguished look",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Elan is a 43-year-old adult male of Indigenous heritage, standing 188cm (6'2\") tall and weighing approximately 118kg (260lbs). He has a very large frame with substantial proportions. His face shows high cheekbones, strong angular features, and proud presence. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin has a healthy mature glow. Elan carries himself with confident adult presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  }
];

// Total: 72 Adult Personas
export default missingAdultPersonas;
