/**
 * KIDS PERSONAS (Ages 6-12)
 * 
 * Complete collection of 112 Kids personas covering:
 * - 56 Kids Female personas (8 ethnicities × 7 sizes)
 * - 56 Kids Male personas (8 ethnicities × 7 sizes)
 * 
 * Key characteristics for Kids:
 * - School-age children (elementary to middle school)
 * - Active, playful energy
 * - Growing but still childlike features
 * - Age-appropriate heights/weights based on pediatric charts
 * 
 * Version: 1.0
 * Created: December 2024
 */

import { Persona, Ethnicity, Size } from '../types';

// ============================================================================
// KIDS FEMALE PERSONAS (56 total)
// ============================================================================

export const KIDS_FEMALE_PERSONAS: Record<Ethnicity, Record<Size, Persona[]>> = {
  
  // WHITE KIDS FEMALES
  'White': {
    'XS': [{ id: 'WHT_KD_F_XS_001', name: 'Emma', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'XS', height: '107cm (3\'6")', weight: '17kg (37lbs)', build: 'Petite slender child frame', facialFeatures: 'Sweet round face with rosy cheeks, bright blue eyes, small button nose, gap-toothed smile', hairStyle: 'Long blonde pigtails', hairColor: 'Golden blonde', eyeColor: 'Blue', skinTone: 'Fair with rosy cheeks', fullDescription: 'Emma is a petite 6-year-old girl, standing 107cm tall and weighing approximately 17kg. She has a petite slender child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features rosy cheeks, bright curious blue eyes, a small button nose, and an adorable gap-toothed smile. Her long golden blonde hair styled in pigtails frames her fair complexion with naturally rosy cheeks.' }],
    'S': [{ id: 'WHT_KD_F_S_001', name: 'Lily', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'S', height: '117cm (3\'10")', weight: '21kg (46lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with freckles, sparkling green eyes, small nose, cheerful smile', hairStyle: 'Shoulder-length light brown with headband', hairColor: 'Light brown', eyeColor: 'Green', skinTone: 'Fair with freckles', fullDescription: 'Lily is an active 7-year-old girl, standing 117cm tall and weighing approximately 21kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features charming freckles across her nose, sparkling green eyes, a small nose, and a cheerful bright smile. Her shoulder-length light brown hair with a colorful headband frames her fair complexion dotted with freckles.' }],
    'M': [{ id: 'WHT_KD_F_M_001', name: 'Sophie', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'M', height: '127cm (4\'2")', weight: '26kg (57lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm hazel eyes, button nose, sweet smile', hairStyle: 'Medium brown ponytail', hairColor: 'Medium brown', eyeColor: 'Hazel', skinTone: 'Light with natural glow', fullDescription: 'Sophie is a friendly 8-year-old girl, standing 127cm tall and weighing approximately 26kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm hazel eyes, a button nose, and a sweet genuine smile. Her medium brown hair in a neat ponytail frames her light complexion with a healthy natural glow.' }],
    'L': [{ id: 'WHT_KD_F_L_001', name: 'Olivia', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'L', height: '137cm (4\'6")', weight: '32kg (71lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with rosy cheeks, bright blue eyes, turned-up nose, warm smile', hairStyle: 'Long dirty blonde braids', hairColor: 'Dirty blonde', eyeColor: 'Blue', skinTone: 'Fair with pink undertones', fullDescription: 'Olivia is a sturdy 9-year-old girl, standing 137cm tall and weighing approximately 32kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features rosy cheeks, bright blue eyes, a cute turned-up nose, and a warm friendly smile. Her long dirty blonde hair in neat braids frames her fair complexion with pink undertones.' }],
    'XL': [{ id: 'WHT_KD_F_XL_001', name: 'Ava', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'XL', height: '142cm (4\'8")', weight: '40kg (88lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with double chin forming, small gray eyes, wide nose, happy smile', hairStyle: 'Medium auburn waves', hairColor: 'Auburn', eyeColor: 'Gray', skinTone: 'Light with flushed cheeks', fullDescription: 'Ava is a larger 10-year-old girl, standing 142cm tall and weighing approximately 40kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features a forming double chin, small gray eyes, a wide nose, and a happy infectious smile. Her medium auburn waves frame her light complexion with naturally flushed cheeks.' }],
    'XXL': [{ id: 'WHT_KD_F_XXL_001', name: 'Grace', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'XXL', height: '147cm (4\'10")', weight: '50kg (110lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small blue eyes, large nose, gentle smile', hairStyle: 'Long light brown', hairColor: 'Light brown', eyeColor: 'Blue', skinTone: 'Fair with soft features', fullDescription: 'Grace is a plus size 11-year-old girl, standing 147cm tall and weighing approximately 50kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small blue eyes, a large nose, and a gentle sweet smile. Her long light brown hair frames her fair complexion with soft, gentle features.' }],
    'XXXL': [{ id: 'WHT_KD_F_XXXL_001', name: 'Hannah', age: 'Kids', sex: 'Female', ethnicity: 'White', size: 'XXXL', height: '152cm (5\'0")', weight: '62kg (137lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins, tiny brown eyes, very wide nose, shy smile', hairStyle: 'Medium brown with clips', hairColor: 'Medium brown', eyeColor: 'Brown', skinTone: 'Light with soft texture', fullDescription: 'Hannah is a very large 12-year-old girl, standing 152cm tall and weighing approximately 62kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny brown eyes, a very wide nose, and a shy but sweet smile. Her medium brown hair with colorful clips frames her light complexion with soft texture.' }]
  },

  // BLACK KIDS FEMALES
  'Black': {
    'XS': [{ id: 'BLK_KD_F_XS_001', name: 'Aaliyah', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'XS', height: '106cm (3\'6")', weight: '17kg (37lbs)', build: 'Petite slender child frame', facialFeatures: 'Sweet round face with bright dark eyes, small nose, adorable gap-toothed smile', hairStyle: 'Two puff balls with colorful beads', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich dark brown with natural glow', fullDescription: 'Aaliyah is a petite 6-year-old girl, standing 106cm tall and weighing approximately 17kg. She has a petite slender child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features bright curious dark eyes, a small nose, and an adorable gap-toothed smile. Her black hair styled in two puff balls with colorful beads frames her rich dark brown complexion with natural healthy glow.' }],
    'S': [{ id: 'BLK_KD_F_S_001', name: 'Zoe', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'S', height: '116cm (3\'10")', weight: '20kg (44lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with high cheekbones, sparkling brown eyes, small nose, bright smile', hairStyle: 'Multiple braids with beads', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Zoe is an active 7-year-old girl, standing 116cm tall and weighing approximately 20kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features high cheekbones, sparkling brown eyes, a small nose, and a bright energetic smile. Her black hair styled in multiple braids with colorful beads frames her medium brown complexion with warm undertones.' }],
    'M': [{ id: 'BLK_KD_F_M_001', name: 'Maya', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'M', height: '126cm (4\'2")', weight: '25kg (55lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, joyful smile', hairStyle: 'Natural curls with headband', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Maya is a friendly 8-year-old girl, standing 126cm tall and weighing approximately 25kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm dark eyes, a button nose, and a joyful infectious smile. Her natural black curls with a colorful headband frame her warm brown complexion with healthy glow.' }],
    'L': [{ id: 'BLK_KD_F_L_001', name: 'Destiny', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'L', height: '136cm (4\'5")', weight: '31kg (68lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with bright eyes, broad nose, beautiful wide smile', hairStyle: 'Long box braids', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich brown with natural radiance', fullDescription: 'Destiny is a sturdy 9-year-old girl, standing 136cm tall and weighing approximately 31kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features bright expressive eyes, a broad nose, and a beautiful wide smile. Her long black box braids frame her rich brown complexion with natural radiance.' }],
    'XL': [{ id: 'BLK_KD_F_XL_001', name: 'Jasmine', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'XL', height: '141cm (4\'7")', weight: '39kg (86lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, warm smile', hairStyle: 'Thick natural puffs', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft features', fullDescription: 'Jasmine is a larger 10-year-old girl, standing 141cm tall and weighing approximately 39kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features round cheeks, small dark eyes, a wide nose, and a warm genuine smile. Her thick black natural hair in two puffs frames her dark brown complexion with soft features.' }],
    'XXL': [{ id: 'BLK_KD_F_XXL_001', name: 'Brianna', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'XXL', height: '146cm (4\'9")', weight: '49kg (108lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small bright eyes, large nose, gentle smile', hairStyle: 'Long braids with extensions', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium dark with warm undertones', fullDescription: 'Brianna is a plus size 11-year-old girl, standing 146cm tall and weighing approximately 49kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small bright eyes, a large nose, and a gentle sweet smile. Her long black braids with extensions frame her medium dark complexion with warm undertones.' }],
    'XXXL': [{ id: 'BLK_KD_F_XXXL_001', name: 'Diamond', age: 'Kids', sex: 'Female', ethnicity: 'Black', size: 'XXXL', height: '151cm (4\'11")', weight: '61kg (134lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy warm smile', hairStyle: 'Natural twists', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich dark brown', fullDescription: 'Diamond is a very large 12-year-old girl, standing 151cm tall and weighing approximately 61kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but warm smile. Her black natural twists frame her rich dark brown complexion.' }]
  },

  // HISPANIC KIDS FEMALES
  'Hispanic': {
    'XS': [{ id: 'HSP_KD_F_XS_001', name: 'Isabella', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'XS', height: '105cm (3\'5")', weight: '16kg (35lbs)', build: 'Petite slender child frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small nose, adorable smile with missing teeth', hairStyle: 'Long dark brown with ribbons', hairColor: 'Dark brown', eyeColor: 'Dark brown', skinTone: 'Warm olive with rosy cheeks', fullDescription: 'Isabella is a petite 6-year-old girl, standing 105cm tall and weighing approximately 16kg. She has a petite slender child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features rosy cheeks, bright curious dark eyes, a small nose, and an adorable smile showing missing teeth. Her long dark brown hair with colorful ribbons frames her warm olive complexion with naturally rosy cheeks.' }],
    'S': [{ id: 'HSP_KD_F_S_001', name: 'Sofia', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'S', height: '115cm (3\'9")', weight: '20kg (44lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with high cheekbones, sparkling brown eyes, small nose, cheerful smile', hairStyle: 'Shoulder-length black wavy', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Light tan with warm glow', fullDescription: 'Sofia is an active 7-year-old girl, standing 115cm tall and weighing approximately 20kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features high cheekbones, sparkling brown eyes, a small nose, and a cheerful bright smile. Her shoulder-length black wavy hair frames her light tan complexion with warm glow.' }],
    'M': [{ id: 'HSP_KD_F_M_001', name: 'Camila', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'M', height: '125cm (4\'1")', weight: '25kg (55lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, sweet smile', hairStyle: 'Long brown ponytail', hairColor: 'Brown', eyeColor: 'Dark brown', skinTone: 'Medium tan with healthy glow', fullDescription: 'Camila is a friendly 8-year-old girl, standing 125cm tall and weighing approximately 25kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm dark eyes, a button nose, and a sweet genuine smile. Her long brown hair in a neat ponytail frames her medium tan complexion with healthy glow.' }],
    'L': [{ id: 'HSP_KD_F_L_001', name: 'Valentina', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'L', height: '135cm (4\'5")', weight: '31kg (68lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with rosy cheeks, bright brown eyes, broad nose, warm smile', hairStyle: 'Long black braids', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Warm brown with natural flush', fullDescription: 'Valentina is a sturdy 9-year-old girl, standing 135cm tall and weighing approximately 31kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features rosy cheeks, bright brown eyes, a broad nose, and a warm friendly smile. Her long black hair in braids frames her warm brown complexion with natural flush.' }],
    'XL': [{ id: 'HSP_KD_F_XL_001', name: 'Lucia', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'XL', height: '140cm (4\'7")', weight: '38kg (84lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, happy smile', hairStyle: 'Medium dark curly', hairColor: 'Dark brown', eyeColor: 'Dark brown', skinTone: 'Olive tan with soft features', fullDescription: 'Lucia is a larger 10-year-old girl, standing 140cm tall and weighing approximately 38kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features round cheeks, small dark eyes, a wide nose, and a happy infectious smile. Her medium dark curly hair frames her olive tan complexion with soft features.' }],
    'XXL': [{ id: 'HSP_KD_F_XXL_001', name: 'Maria', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'XXL', height: '145cm (4\'9")', weight: '48kg (106lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small brown eyes, large nose, gentle smile', hairStyle: 'Long black waves', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Warm tan with soft features', fullDescription: 'Maria is a plus size 11-year-old girl, standing 145cm tall and weighing approximately 48kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small brown eyes, a large nose, and a gentle sweet smile. Her long black waves frame her warm tan complexion with soft features.' }],
    'XXXL': [{ id: 'HSP_KD_F_XXXL_001', name: 'Gabriela', age: 'Kids', sex: 'Female', ethnicity: 'Hispanic', size: 'XXXL', height: '150cm (4\'11")', weight: '60kg (132lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Medium brown with clips', hairColor: 'Brown', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft texture', fullDescription: 'Gabriela is a very large 12-year-old girl, standing 150cm tall and weighing approximately 60kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but sweet smile. Her medium brown hair with colorful clips frames her medium brown complexion with soft texture.' }]
  },

  // ASIAN KIDS FEMALES
  'Asian': {
    'XS': [{ id: 'ASN_KD_F_XS_001', name: 'Yuki', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'XS', height: '104cm (3\'5")', weight: '15kg (33lbs)', build: 'Petite delicate child frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small flat nose, adorable smile', hairStyle: 'Short black bob with bangs', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with porcelain quality', fullDescription: 'Yuki is a petite 6-year-old girl, standing 104cm tall and weighing approximately 15kg. She has a petite delicate child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features rosy cheeks, bright curious dark eyes, a small flat nose, and an adorable sweet smile. Her short black bob with bangs frames her fair complexion with porcelain quality.' }],
    'S': [{ id: 'ASN_KD_F_S_001', name: 'Mei', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'S', height: '114cm (3\'9")', weight: '19kg (42lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with high cheekbones, sparkling almond eyes, small nose, bright smile', hairStyle: 'Long black with colorful clips', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light with golden undertones', fullDescription: 'Mei is an active 7-year-old girl, standing 114cm tall and weighing approximately 19kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features high cheekbones, sparkling almond-shaped eyes, a small nose, and a bright cheerful smile. Her long black hair with colorful clips frames her light complexion with golden undertones.' }],
    'M': [{ id: 'ASN_KD_F_M_001', name: 'Hana', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'M', height: '124cm (4\'1")', weight: '24kg (53lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, sweet smile', hairStyle: 'Medium black ponytail', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium fair with natural glow', fullDescription: 'Hana is a friendly 8-year-old girl, standing 124cm tall and weighing approximately 24kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm dark eyes, a button nose, and a sweet genuine smile. Her medium black hair in a ponytail frames her medium fair complexion with natural healthy glow.' }],
    'L': [{ id: 'ASN_KD_F_L_001', name: 'Sakura', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'L', height: '134cm (4\'5")', weight: '30kg (66lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with rosy cheeks, bright dark eyes, small nose, warm smile', hairStyle: 'Long black with headband', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm beige with natural flush', fullDescription: 'Sakura is a sturdy 9-year-old girl, standing 134cm tall and weighing approximately 30kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features rosy cheeks, bright dark eyes, a small nose, and a warm friendly smile. Her long black hair with colorful headband frames her warm beige complexion with natural flush.' }],
    'XL': [{ id: 'ASN_KD_F_XL_001', name: 'Lin', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'XL', height: '139cm (4\'7")', weight: '37kg (82lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide flat nose, happy smile', hairStyle: 'Medium black layers', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with soft features', fullDescription: 'Lin is a larger 10-year-old girl, standing 139cm tall and weighing approximately 37kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features round cheeks, small dark eyes, a wide flat nose, and a happy smile. Her medium black hair in layers frames her fair complexion with soft features.' }],
    'XXL': [{ id: 'ASN_KD_F_XXL_001', name: 'Ai', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'XXL', height: '144cm (4\'9")', weight: '46kg (101lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small dark eyes, large flat nose, gentle smile', hairStyle: 'Long black straight', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light with soft texture', fullDescription: 'Ai is a plus size 11-year-old girl, standing 144cm tall and weighing approximately 46kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small dark eyes, a large flat nose, and a gentle sweet smile. Her long black straight hair frames her light complexion with soft texture.' }],
    'XXXL': [{ id: 'ASN_KD_F_XXXL_001', name: 'Yuna', age: 'Kids', sex: 'Female', ethnicity: 'Asian', size: 'XXXL', height: '149cm (4\'11")', weight: '57kg (126lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Medium black with barrettes', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with soft features', fullDescription: 'Yuna is a very large 12-year-old girl, standing 149cm tall and weighing approximately 57kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but sweet smile. Her medium black hair with barrettes frames her fair complexion with soft features.' }]
  },

  // INDIAN KIDS FEMALES
  'Indian': {
    'XS': [{ id: 'IND_KD_F_XS_001', name: 'Priya', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'XS', height: '104cm (3\'5")', weight: '15kg (33lbs)', build: 'Petite delicate child frame', facialFeatures: 'Sweet round face with bright dark eyes, small nose, adorable smile', hairStyle: 'Long black braids with ribbons', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Priya is a petite 6-year-old girl, standing 104cm tall and weighing approximately 15kg. She has a petite delicate child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features bright curious dark eyes, a small nose, and an adorable sweet smile. Her long black hair in braids with colorful ribbons frames her warm brown complexion with healthy glow.' }],
    'S': [{ id: 'IND_KD_F_S_001', name: 'Ananya', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'S', height: '114cm (3\'9")', weight: '19kg (42lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with high cheekbones, sparkling dark eyes, small nose, bright smile', hairStyle: 'Long black ponytail', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Ananya is an active 7-year-old girl, standing 114cm tall and weighing approximately 19kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features high cheekbones, sparkling dark eyes, a small nose, and a bright cheerful smile. Her long black hair in a neat ponytail frames her medium brown complexion with warm undertones.' }],
    'M': [{ id: 'IND_KD_F_M_001', name: 'Divya', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'M', height: '124cm (4\'1")', weight: '24kg (53lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, sweet smile', hairStyle: 'Long black with clips', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm tan with natural glow', fullDescription: 'Divya is a friendly 8-year-old girl, standing 124cm tall and weighing approximately 24kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm dark eyes, a button nose, and a sweet genuine smile. Her long black hair with colorful clips frames her warm tan complexion with natural healthy glow.' }],
    'L': [{ id: 'IND_KD_F_L_001', name: 'Lakshmi', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'L', height: '134cm (4\'5")', weight: '29kg (64lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with bright eyes, broad nose, warm smile', hairStyle: 'Long black braids', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with natural radiance', fullDescription: 'Lakshmi is a sturdy 9-year-old girl, standing 134cm tall and weighing approximately 29kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features bright expressive eyes, a broad nose, and a warm friendly smile. Her long black hair in braids frames her dark brown complexion with natural radiance.' }],
    'XL': [{ id: 'IND_KD_F_XL_001', name: 'Meera', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'XL', height: '139cm (4\'7")', weight: '36kg (79lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, happy smile', hairStyle: 'Medium black waves', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft features', fullDescription: 'Meera is a larger 10-year-old girl, standing 139cm tall and weighing approximately 36kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features round cheeks, small dark eyes, a wide nose, and a happy warm smile. Her medium black wavy hair frames her medium brown complexion with soft features.' }],
    'XXL': [{ id: 'IND_KD_F_XXL_001', name: 'Sita', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'XXL', height: '144cm (4\'9")', weight: '45kg (99lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small bright eyes, large nose, gentle smile', hairStyle: 'Long black with hair tie', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with soft features', fullDescription: 'Sita is a plus size 11-year-old girl, standing 144cm tall and weighing approximately 45kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small bright eyes, a large nose, and a gentle sweet smile. Her long black hair with colorful hair tie frames her warm brown complexion with soft features.' }],
    'XXXL': [{ id: 'IND_KD_F_XXXL_001', name: 'Padma', age: 'Kids', sex: 'Female', ethnicity: 'Indian', size: 'XXXL', height: '149cm (4\'11")', weight: '56kg (123lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Medium black braided', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft texture', fullDescription: 'Padma is a very large 12-year-old girl, standing 149cm tall and weighing approximately 56kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but sweet smile. Her medium black braided hair frames her dark brown complexion with soft texture.' }]
  },

  // SOUTHEAST ASIAN KIDS FEMALES
  'Southeast Asian': {
    'XS': [{ id: 'SEA_KD_F_XS_001', name: 'Linh', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'XS', height: '102cm (3\'4")', weight: '14kg (31lbs)', build: 'Petite delicate child frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small flat nose, adorable smile', hairStyle: 'Short black bob', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light tan with natural glow', fullDescription: 'Linh is a petite 6-year-old girl, standing 102cm tall and weighing approximately 14kg. She has a petite delicate child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features rosy cheeks, bright curious dark eyes, a small flat nose, and an adorable sweet smile. Her short black bob frames her light tan complexion with natural glow.' }],
    'S': [{ id: 'SEA_KD_F_S_001', name: 'Mai', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'S', height: '112cm (3\'8")', weight: '18kg (40lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with high cheekbones, sparkling dark eyes, small nose, bright smile', hairStyle: 'Long black with colorful bands', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium tan with warm undertones', fullDescription: 'Mai is an active 7-year-old girl, standing 112cm tall and weighing approximately 18kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features high cheekbones, sparkling dark eyes, a small nose, and a bright cheerful smile. Her long black hair with colorful bands frames her medium tan complexion with warm undertones.' }],
    'M': [{ id: 'SEA_KD_F_M_001', name: 'Hoa', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'M', height: '122cm (4\'0")', weight: '23kg (51lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, sweet smile', hairStyle: 'Medium black ponytail', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm tan with healthy glow', fullDescription: 'Hoa is a friendly 8-year-old girl, standing 122cm tall and weighing approximately 23kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features adorable dimples, warm dark eyes, a button nose, and a sweet genuine smile. Her medium black hair in a ponytail frames her warm tan complexion with healthy glow.' }],
    'L': [{ id: 'SEA_KD_F_L_001', name: 'Lan', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'L', height: '132cm (4\'4")', weight: '28kg (62lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with bright eyes, broad nose, warm smile', hairStyle: 'Long black with clips', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with natural radiance', fullDescription: 'Lan is a sturdy 9-year-old girl, standing 132cm tall and weighing approximately 28kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features bright expressive eyes, a broad nose, and a warm friendly smile. Her long black hair with colorful clips frames her medium brown complexion with natural radiance.' }],
    'XL': [{ id: 'SEA_KD_F_XL_001', name: 'Thuy', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'XL', height: '137cm (4\'6")', weight: '35kg (77lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide flat nose, happy smile', hairStyle: 'Medium black waves', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Tan with soft features', fullDescription: 'Thuy is a larger 10-year-old girl, standing 137cm tall and weighing approximately 35kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features round cheeks, small dark eyes, a wide flat nose, and a happy warm smile. Her medium black wavy hair frames her tan complexion with soft features.' }],
    'XXL': [{ id: 'SEA_KD_F_XXL_001', name: 'Nguyet', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'XXL', height: '142cm (4\'8")', weight: '44kg (97lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with chubby cheeks, small dark eyes, large flat nose, gentle smile', hairStyle: 'Long black straight', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium tan with soft texture', fullDescription: 'Nguyet is a plus size 11-year-old girl, standing 142cm tall and weighing approximately 44kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features chubby cheeks, small dark eyes, a large flat nose, and a gentle sweet smile. Her long black straight hair frames her medium tan complexion with soft texture.' }],
    'XXXL': [{ id: 'SEA_KD_F_XXXL_001', name: 'Thi', age: 'Kids', sex: 'Female', ethnicity: 'Southeast Asian', size: 'XXXL', height: '147cm (4\'10")', weight: '55kg (121lbs)', build: 'Very large child frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Medium black with barrettes', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Tan with soft features', fullDescription: 'Thi is a very large 12-year-old girl, standing 147cm tall and weighing approximately 55kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but sweet smile. Her medium black hair with barrettes frames her tan complexion with soft features.' }]
  },

  // INDIGENOUS KIDS FEMALES
  'Indigenous': {
    'XS': [{ id: 'IND_KD_F_XS_001', name: 'Kaya', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'XS', height: '105cm (3\'5")', weight: '16kg (35lbs)', build: 'Petite sturdy child frame', facialFeatures: 'Sweet round face with high cheekbones, bright dark eyes, small nose, adorable smile', hairStyle: 'Long black braids with beads', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm reddish-brown with natural glow', fullDescription: 'Kaya is a petite 6-year-old girl, standing 105cm tall and weighing approximately 16kg. She has a petite sturdy child frame with small shoulders, thin arms, flat tummy, and slim legs. Her sweet round face features high cheekbones, bright curious dark eyes, a small nose, and an adorable sweet smile. Her long black braids with colorful beads frame her warm reddish-brown complexion with natural glow.' }],
    'S': [{ id: 'IND_KD_F_S_001', name: 'Aiyana', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'S', height: '115cm (3\'9")', weight: '20kg (44lbs)', build: 'Slim active child frame', facialFeatures: 'Oval face with prominent cheekbones, sparkling brown eyes, straight nose, bright smile', hairStyle: 'Long black with ribbon', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Aiyana is an active 7-year-old girl, standing 115cm tall and weighing approximately 20kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features prominent cheekbones, sparkling brown eyes, a straight nose, and a bright cheerful smile. Her long black hair with traditional ribbon frames her medium brown complexion with warm undertones.' }],
    'M': [{ id: 'IND_KD_F_M_001', name: 'Naya', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'M', height: '125cm (4\'1")', weight: '25kg (55lbs)', build: 'Average healthy child frame', facialFeatures: 'Round friendly face with high cheekbones, warm dark eyes, broad nose, sweet smile', hairStyle: 'Long black ponytail', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Naya is a friendly 8-year-old girl, standing 125cm tall and weighing approximately 25kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features high cheekbones, warm dark eyes, a broad nose, and a sweet genuine smile. Her long black hair in a ponytail frames her warm brown complexion with healthy glow.' }],
    'L': [{ id: 'IND_KD_F_L_001', name: 'Winona', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'L', height: '135cm (4\'5")', weight: '31kg (68lbs)', build: 'Sturdy well-built child frame', facialFeatures: 'Full round face with strong cheekbones, bright dark eyes, strong nose, warm smile', hairStyle: 'Long black braids', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark reddish-brown with natural radiance', fullDescription: 'Winona is a sturdy 9-year-old girl, standing 135cm tall and weighing approximately 31kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features strong cheekbones, bright dark eyes, a strong nose, and a warm friendly smile. Her long black braids frame her dark reddish-brown complexion with natural radiance.' }],
    'XL': [{ id: 'IND_KD_F_XL_001', name: 'Mika', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'XL', height: '140cm (4\'7")', weight: '38kg (84lbs)', build: 'Larger husky child frame', facialFeatures: 'Full chubby face with high cheekbones, small dark eyes, wide nose, happy smile', hairStyle: 'Medium black waves', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich brown with soft features', fullDescription: 'Mika is a larger 10-year-old girl, standing 140cm tall and weighing approximately 38kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features high cheekbones, small dark eyes, a wide nose, and a happy warm smile. Her medium black wavy hair frames her rich brown complexion with soft features.' }],
    'XXL': [{ id: 'IND_KD_F_XXL_001', name: 'Tala', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'XXL', height: '145cm (4\'9")', weight: '47kg (104lbs)', build: 'Plus size child frame', facialFeatures: 'Very full round face with prominent cheekbones, small bright eyes, large nose, gentle smile', hairStyle: 'Long black with clips', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft texture', fullDescription: 'Tala is a plus size 11-year-old girl, standing 145cm tall and weighing approximately 47kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features prominent cheekbones, small bright eyes, a large nose, and a gentle sweet smile. Her long black hair with colorful clips frames her medium brown complexion with soft texture.' }],
    'XXXL': [{ id: 'IND_KD_F_XXXL_001', name: 'Nina', age: 'Kids', sex: 'Female', ethnicity: 'Indigenous', size: 'XXXL', height: '150cm (4\'11")', weight: '59kg (130lbs)', build: 'Very large child frame', facialFeatures: 'Very full strong face with high cheekbones, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Medium black braided', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft features', fullDescription: 'Nina is a very large 12-year-old girl, standing 150cm tall and weighing approximately 59kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full strong face features high cheekbones, tiny dark eyes, a very wide nose, and a shy but sweet smile. Her medium black braided hair frames her dark brown complexion with soft features.' }]
  },

  // DIVERSE KIDS FEMALES
  'Diverse': {
    'XS': [{ id: 'DIV_KD_F_XS_001', name: 'Zara', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'XS', height: '105cm (3\'5")', weight: '16kg (35lbs)', build: 'Petite slender child frame with mixed heritage', facialFeatures: 'Sweet round face with unique blended features, bright hazel eyes, small nose, adorable smile', hairStyle: 'Curly brown with colorful bands', hairColor: 'Light brown with golden highlights', eyeColor: 'Hazel', skinTone: 'Warm caramel with natural glow', fullDescription: 'Zara is a petite 6-year-old girl of mixed heritage, standing 105cm tall and weighing approximately 16kg. She has a petite slender child frame with small shoulders, thin arms, flat tummy, and skinny legs. Her sweet round face features unique blended features, bright curious hazel eyes, a small nose, and an adorable sweet smile. Her curly light brown hair with golden highlights and colorful bands frames her warm caramel complexion with natural glow.' }],
    'S': [{ id: 'DIV_KD_F_S_001', name: 'Luna', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'S', height: '115cm (3\'9")', weight: '20kg (44lbs)', build: 'Slim active child frame with multicultural features', facialFeatures: 'Oval face with exotic blend, sparkling amber eyes, distinctive nose, bright smile', hairStyle: 'Long wavy dark brown', hairColor: 'Dark brown with auburn hints', eyeColor: 'Amber', skinTone: 'Golden tan with warm undertones', fullDescription: 'Luna is an active 7-year-old girl of diverse background, standing 115cm tall and weighing approximately 20kg. She has a slim active child frame with narrow shoulders, slender arms, flat tummy, and slim legs. Her oval face features an exotic blend of features, sparkling amber eyes, a distinctive nose, and a bright cheerful smile. Her long wavy dark brown hair with auburn hints frames her golden tan complexion with warm undertones.' }],
    'M': [{ id: 'DIV_KD_F_M_001', name: 'Aria', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'M', height: '125cm (4\'1")', weight: '25kg (55lbs)', build: 'Average healthy child frame with beautiful mixed features', facialFeatures: 'Round friendly face with blended heritage, warm brown-green eyes, button nose, sweet smile', hairStyle: 'Medium curly with headband', hairColor: 'Brown with natural highlights', eyeColor: 'Brown-green', skinTone: 'Warm olive with healthy glow', fullDescription: 'Aria is a friendly 8-year-old girl of mixed ancestry, standing 125cm tall and weighing approximately 25kg. She has an average healthy child frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. Her round friendly face features beautiful blended heritage, warm brown-green eyes, a button nose, and a sweet genuine smile. Her medium curly brown hair with natural highlights and colorful headband frames her warm olive complexion with healthy glow.' }],
    'L': [{ id: 'DIV_KD_F_L_001', name: 'Mila', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'L', height: '135cm (4\'5")', weight: '31kg (68lbs)', build: 'Sturdy well-built child frame with multicultural presence', facialFeatures: 'Full round face with striking blend, bright golden-brown eyes, broad nose, warm smile', hairStyle: 'Long curly with clips', hairColor: 'Dark brown with copper highlights', eyeColor: 'Golden-brown', skinTone: 'Rich olive with natural radiance', fullDescription: 'Mila is a sturdy 9-year-old girl of diverse heritage, standing 135cm tall and weighing approximately 31kg. She has a sturdy well-built child frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. Her full round face features a striking blend of features, bright golden-brown eyes, a broad nose, and a warm friendly smile. Her long curly dark brown hair with copper highlights and colorful clips frames her rich olive complexion with natural radiance.' }],
    'XL': [{ id: 'DIV_KD_F_XL_001', name: 'Amara', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'XL', height: '140cm (4\'7")', weight: '38kg (84lbs)', build: 'Larger husky child frame with unique heritage blend', facialFeatures: 'Full chubby face with exotic features, small warm eyes, wide nose, happy smile', hairStyle: 'Medium curly waves', hairColor: 'Dark with golden streaks', eyeColor: 'Warm brown', skinTone: 'Warm bronze with soft features', fullDescription: 'Amara is a larger 10-year-old girl of mixed heritage, standing 140cm tall and weighing approximately 38kg. She has a larger husky child frame with wide shoulders, thick arms, rounded belly, and thick legs. Her full chubby face features exotic blend of features, small warm eyes, a wide nose, and a happy infectious smile. Her medium curly dark hair with golden streaks frames her warm bronze complexion with soft features.' }],
    'XXL': [{ id: 'DIV_KD_F_XXL_001', name: 'Nia', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'XXL', height: '145cm (4\'9")', weight: '47kg (104lbs)', build: 'Plus size child frame with beautiful multicultural features', facialFeatures: 'Very full round face with complex heritage, small bright eyes, large nose, gentle smile', hairStyle: 'Long wavy with barrettes', hairColor: 'Brown with highlights', eyeColor: 'Brown', skinTone: 'Medium tan with soft texture', fullDescription: 'Nia is a plus size 11-year-old girl of diverse ancestry, standing 145cm tall and weighing approximately 47kg. She has a plus size child frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. Her very full round face features complex heritage blend, small bright eyes, a large nose, and a gentle sweet smile. Her long wavy brown hair with highlights and barrettes frames her medium tan complexion with soft texture.' }],
    'XXXL': [{ id: 'DIV_KD_F_XXXL_001', name: 'Jasmine', age: 'Kids', sex: 'Female', ethnicity: 'Diverse', size: 'XXXL', height: '150cm (4\'11")', weight: '59kg (130lbs)', build: 'Very large child frame with beautiful blended heritage', facialFeatures: 'Very full face with unique mixed features, tiny bright eyes, very wide nose, shy warm smile', hairStyle: 'Medium curly with clips', hairColor: 'Dark brown with golden highlights', eyeColor: 'Brown-hazel', skinTone: 'Warm caramel with soft features', fullDescription: 'Jasmine is a very large 12-year-old girl of mixed heritage, standing 150cm tall and weighing approximately 59kg. She has a very large child frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. Her very full face features unique blended features, tiny bright eyes, a very wide nose, and a shy but warm smile. Her medium curly dark brown hair with golden highlights and colorful clips frames her warm caramel complexion with soft features.' }]
  }
};

// ============================================================================
// KIDS MALE PERSONAS (56 total)
// ============================================================================

export const KIDS_MALE_PERSONAS: Record<Ethnicity, Record<Size, Persona[]>> = {
  
  // WHITE KIDS MALES
  'White': {
    'XS': [{ id: 'WHT_KD_M_XS_001', name: 'Ethan', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'XS', height: '109cm (3\'7")', weight: '18kg (40lbs)', build: 'Petite slender boy frame', facialFeatures: 'Sweet round face with rosy cheeks, bright blue eyes, small nose, gap-toothed grin', hairStyle: 'Short blonde messy', hairColor: 'Golden blonde', eyeColor: 'Blue', skinTone: 'Fair with rosy cheeks', fullDescription: 'Ethan is a petite 6-year-old boy, standing 109cm tall and weighing approximately 18kg. He has a petite slender boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features rosy cheeks, bright curious blue eyes, a small nose, and an adorable gap-toothed grin. His short messy golden blonde hair frames his fair complexion with naturally rosy cheeks.' }],
    'S': [{ id: 'WHT_KD_M_S_001', name: 'Liam', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'S', height: '119cm (3\'11")', weight: '22kg (49lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with freckles, sparkling green eyes, small nose, mischievous smile', hairStyle: 'Short light brown with cowlick', hairColor: 'Light brown', eyeColor: 'Green', skinTone: 'Fair with freckles', fullDescription: 'Liam is an active 7-year-old boy, standing 119cm tall and weighing approximately 22kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features charming freckles across his nose, sparkling green eyes, a small nose, and a mischievous smile. His short light brown hair with a cowlick frames his fair complexion dotted with freckles.' }],
    'M': [{ id: 'WHT_KD_M_M_001', name: 'Noah', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'M', height: '129cm (4\'3")', weight: '27kg (60lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm hazel eyes, button nose, cheerful smile', hairStyle: 'Medium brown neat', hairColor: 'Medium brown', eyeColor: 'Hazel', skinTone: 'Light with natural glow', fullDescription: 'Noah is a friendly 8-year-old boy, standing 129cm tall and weighing approximately 27kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm hazel eyes, a button nose, and a cheerful genuine smile. His medium brown hair neatly styled frames his light complexion with a healthy natural glow.' }],
    'L': [{ id: 'WHT_KD_M_L_001', name: 'Oliver', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'L', height: '139cm (4\'7")', weight: '34kg (75lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with rosy cheeks, bright blue eyes, turned-up nose, warm grin', hairStyle: 'Short dirty blonde', hairColor: 'Dirty blonde', eyeColor: 'Blue', skinTone: 'Fair with pink undertones', fullDescription: 'Oliver is a sturdy 9-year-old boy, standing 139cm tall and weighing approximately 34kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features rosy cheeks, bright blue eyes, a cute turned-up nose, and a warm friendly grin. His short dirty blonde hair frames his fair complexion with pink undertones.' }],
    'XL': [{ id: 'WHT_KD_M_XL_001', name: 'William', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'XL', height: '144cm (4\'9")', weight: '42kg (93lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with double chin forming, small gray eyes, wide nose, happy grin', hairStyle: 'Medium auburn waves', hairColor: 'Auburn', eyeColor: 'Gray', skinTone: 'Light with flushed cheeks', fullDescription: 'William is a larger 10-year-old boy, standing 144cm tall and weighing approximately 42kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features a forming double chin, small gray eyes, a wide nose, and a happy infectious grin. His medium auburn wavy hair frames his light complexion with naturally flushed cheeks.' }],
    'XXL': [{ id: 'WHT_KD_M_XXL_001', name: 'James', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'XXL', height: '149cm (4\'11")', weight: '52kg (115lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small blue eyes, large nose, gentle smile', hairStyle: 'Short light brown', hairColor: 'Light brown', eyeColor: 'Blue', skinTone: 'Fair with soft features', fullDescription: 'James is a plus size 11-year-old boy, standing 149cm tall and weighing approximately 52kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small blue eyes, a large nose, and a gentle sweet smile. His short light brown hair frames his fair complexion with soft, gentle features.' }],
    'XXXL': [{ id: 'WHT_KD_M_XXXL_001', name: 'Benjamin', age: 'Kids', sex: 'Male', ethnicity: 'White', size: 'XXXL', height: '154cm (5\'1")', weight: '65kg (143lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins, tiny brown eyes, very wide nose, shy smile', hairStyle: 'Short medium brown', hairColor: 'Medium brown', eyeColor: 'Brown', skinTone: 'Light with soft texture', fullDescription: 'Benjamin is a very large 12-year-old boy, standing 154cm tall and weighing approximately 65kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny brown eyes, a very wide nose, and a shy but friendly smile. His short medium brown hair frames his light complexion with soft texture.' }]
  },

  // BLACK KIDS MALES
  'Black': {
    'XS': [{ id: 'BLK_KD_M_XS_001', name: 'Jayden', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'XS', height: '108cm (3\'6.5")', weight: '18kg (40lbs)', build: 'Petite slender boy frame', facialFeatures: 'Sweet round face with bright dark eyes, small nose, adorable gap-toothed grin', hairStyle: 'Short black curls', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich dark brown with natural glow', fullDescription: 'Jayden is a petite 6-year-old boy, standing 108cm tall and weighing approximately 18kg. He has a petite slender boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features bright curious dark eyes, a small nose, and an adorable gap-toothed grin. His short black curls frame his rich dark brown complexion with natural healthy glow.' }],
    'S': [{ id: 'BLK_KD_M_S_001', name: 'Malik', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'S', height: '118cm (3\'10.5")', weight: '21kg (46lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with high cheekbones, sparkling brown eyes, small nose, energetic smile', hairStyle: 'Short fade with curls on top', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Malik is an active 7-year-old boy, standing 118cm tall and weighing approximately 21kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features high cheekbones, sparkling brown eyes, a small nose, and an energetic bright smile. His short black hair with a fade and curls on top frames his medium brown complexion with warm undertones.' }],
    'M': [{ id: 'BLK_KD_M_M_001', name: 'Jordan', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'M', height: '128cm (4\'2.5")', weight: '26kg (57lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, joyful grin', hairStyle: 'Short black twists', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Jordan is a friendly 8-year-old boy, standing 128cm tall and weighing approximately 26kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm dark eyes, a button nose, and a joyful infectious grin. His short black twists frame his warm brown complexion with healthy glow.' }],
    'L': [{ id: 'BLK_KD_M_L_001', name: 'Xavier', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'L', height: '138cm (4\'6")', weight: '33kg (73lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with bright eyes, broad nose, confident wide smile', hairStyle: 'Short black fade', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich brown with natural radiance', fullDescription: 'Xavier is a sturdy 9-year-old boy, standing 138cm tall and weighing approximately 33kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features bright expressive eyes, a broad nose, and a confident wide smile. His short black fade frames his rich brown complexion with natural radiance.' }],
    'XL': [{ id: 'BLK_KD_M_XL_001', name: 'DeShawn', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'XL', height: '143cm (4\'8")', weight: '41kg (90lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, warm grin', hairStyle: 'Short black waves', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft features', fullDescription: 'DeShawn is a larger 10-year-old boy, standing 143cm tall and weighing approximately 41kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features round cheeks, small dark eyes, a wide nose, and a warm genuine grin. His short black wavy hair frames his dark brown complexion with soft features.' }],
    'XXL': [{ id: 'BLK_KD_M_XXL_001', name: 'Terrence', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'XXL', height: '148cm (4\'10")', weight: '51kg (112lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small bright eyes, large nose, gentle smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium dark with warm undertones', fullDescription: 'Terrence is a plus size 11-year-old boy, standing 148cm tall and weighing approximately 51kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small bright eyes, a large nose, and a gentle friendly smile. His short black hair frames his medium dark complexion with warm undertones.' }],
    'XXXL': [{ id: 'BLK_KD_M_XXXL_001', name: 'Marcus', age: 'Kids', sex: 'Male', ethnicity: 'Black', size: 'XXXL', height: '153cm (5\'0")', weight: '64kg (141lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy warm smile', hairStyle: 'Short black buzz', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich dark brown', fullDescription: 'Marcus is a very large 12-year-old boy, standing 153cm tall and weighing approximately 64kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but warm smile. His short black buzz cut frames his rich dark brown complexion.' }]
  },

  // HISPANIC KIDS MALES
  'Hispanic': {
    'XS': [{ id: 'HSP_KD_M_XS_001', name: 'Diego', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'XS', height: '107cm (3\'6")', weight: '17kg (37lbs)', build: 'Petite slender boy frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small nose, adorable grin with missing teeth', hairStyle: 'Short dark brown neat', hairColor: 'Dark brown', eyeColor: 'Dark brown', skinTone: 'Warm olive with rosy cheeks', fullDescription: 'Diego is a petite 6-year-old boy, standing 107cm tall and weighing approximately 17kg. He has a petite slender boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features rosy cheeks, bright curious dark eyes, a small nose, and an adorable grin showing missing teeth. His short neat dark brown hair frames his warm olive complexion with naturally rosy cheeks.' }],
    'S': [{ id: 'HSP_KD_M_S_001', name: 'Mateo', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'S', height: '117cm (3\'10")', weight: '21kg (46lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with high cheekbones, sparkling brown eyes, small nose, mischievous smile', hairStyle: 'Short black wavy', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Light tan with warm glow', fullDescription: 'Mateo is an active 7-year-old boy, standing 117cm tall and weighing approximately 21kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features high cheekbones, sparkling brown eyes, a small nose, and a mischievous bright smile. His short black wavy hair frames his light tan complexion with warm glow.' }],
    'M': [{ id: 'HSP_KD_M_M_001', name: 'Santiago', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'M', height: '127cm (4\'2")', weight: '26kg (57lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, cheerful grin', hairStyle: 'Short brown styled', hairColor: 'Brown', eyeColor: 'Dark brown', skinTone: 'Medium tan with healthy glow', fullDescription: 'Santiago is a friendly 8-year-old boy, standing 127cm tall and weighing approximately 26kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm dark eyes, a button nose, and a cheerful genuine grin. His short brown styled hair frames his medium tan complexion with healthy glow.' }],
    'L': [{ id: 'HSP_KD_M_L_001', name: 'Carlos', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'L', height: '137cm (4\'6")', weight: '32kg (71lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with rosy cheeks, bright brown eyes, broad nose, warm smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Warm brown with natural flush', fullDescription: 'Carlos is a sturdy 9-year-old boy, standing 137cm tall and weighing approximately 32kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features rosy cheeks, bright brown eyes, a broad nose, and a warm friendly smile. His short black hair frames his warm brown complexion with natural flush.' }],
    'XL': [{ id: 'HSP_KD_M_XL_001', name: 'Miguel', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'XL', height: '142cm (4\'8")', weight: '40kg (88lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, happy grin', hairStyle: 'Medium dark curly', hairColor: 'Dark brown', eyeColor: 'Dark brown', skinTone: 'Olive tan with soft features', fullDescription: 'Miguel is a larger 10-year-old boy, standing 142cm tall and weighing approximately 40kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features round cheeks, small dark eyes, a wide nose, and a happy infectious grin. His medium dark curly hair frames his olive tan complexion with soft features.' }],
    'XXL': [{ id: 'HSP_KD_M_XXL_001', name: 'Jose', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'XXL', height: '147cm (4\'10")', weight: '50kg (110lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small brown eyes, large nose, gentle smile', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Warm tan with soft features', fullDescription: 'Jose is a plus size 11-year-old boy, standing 147cm tall and weighing approximately 50kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small brown eyes, a large nose, and a gentle sweet smile. His short black neat hair frames his warm tan complexion with soft features.' }],
    'XXXL': [{ id: 'HSP_KD_M_XXXL_001', name: 'Fernando', age: 'Kids', sex: 'Male', ethnicity: 'Hispanic', size: 'XXXL', height: '152cm (5\'0")', weight: '62kg (137lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy grin', hairStyle: 'Short brown', hairColor: 'Brown', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft texture', fullDescription: 'Fernando is a very large 12-year-old boy, standing 152cm tall and weighing approximately 62kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but friendly grin. His short brown hair frames his medium brown complexion with soft texture.' }]
  },

  // ASIAN KIDS MALES
  'Asian': {
    'XS': [{ id: 'ASN_KD_M_XS_001', name: 'Kenji', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'XS', height: '106cm (3\'6")', weight: '16kg (35lbs)', build: 'Petite delicate boy frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small flat nose, adorable grin', hairStyle: 'Short black with bangs', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with porcelain quality', fullDescription: 'Kenji is a petite 6-year-old boy, standing 106cm tall and weighing approximately 16kg. He has a petite delicate boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features rosy cheeks, bright curious dark eyes, a small flat nose, and an adorable sweet grin. His short black hair with bangs frames his fair complexion with porcelain quality.' }],
    'S': [{ id: 'ASN_KD_M_S_001', name: 'Hiroshi', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'S', height: '116cm (3\'9.5")', weight: '20kg (44lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with high cheekbones, sparkling almond eyes, small nose, cheerful smile', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light with golden undertones', fullDescription: 'Hiroshi is an active 7-year-old boy, standing 116cm tall and weighing approximately 20kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features high cheekbones, sparkling almond-shaped eyes, a small nose, and a cheerful bright smile. His short black neat hair frames his light complexion with golden undertones.' }],
    'M': [{ id: 'ASN_KD_M_M_001', name: 'Takashi', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'M', height: '126cm (4\'1.5")', weight: '25kg (55lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, cheerful grin', hairStyle: 'Short black styled', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium fair with natural glow', fullDescription: 'Takashi is a friendly 8-year-old boy, standing 126cm tall and weighing approximately 25kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm dark eyes, a button nose, and a cheerful genuine grin. His short black styled hair frames his medium fair complexion with natural healthy glow.' }],
    'L': [{ id: 'ASN_KD_M_L_001', name: 'Ryu', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'L', height: '136cm (4\'5.5")', weight: '31kg (68lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with rosy cheeks, bright dark eyes, small nose, warm smile', hairStyle: 'Short black spiky', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm beige with natural flush', fullDescription: 'Ryu is a sturdy 9-year-old boy, standing 136cm tall and weighing approximately 31kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features rosy cheeks, bright dark eyes, a small nose, and a warm friendly smile. His short black spiky hair frames his warm beige complexion with natural flush.' }],
    'XL': [{ id: 'ASN_KD_M_XL_001', name: 'Wei', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'XL', height: '141cm (4\'7.5")', weight: '38kg (84lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide flat nose, happy grin', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with soft features', fullDescription: 'Wei is a larger 10-year-old boy, standing 141cm tall and weighing approximately 38kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features round cheeks, small dark eyes, a wide flat nose, and a happy grin. His short black hair frames his fair complexion with soft features.' }],
    'XXL': [{ id: 'ASN_KD_M_XXL_001', name: 'Chen', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'XXL', height: '146cm (4\'9.5")', weight: '48kg (106lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small dark eyes, large flat nose, gentle smile', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light with soft texture', fullDescription: 'Chen is a plus size 11-year-old boy, standing 146cm tall and weighing approximately 48kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small dark eyes, a large flat nose, and a gentle sweet smile. His short black neat hair frames his light complexion with soft texture.' }],
    'XXXL': [{ id: 'ASN_KD_M_XXXL_001', name: 'Tao', age: 'Kids', sex: 'Male', ethnicity: 'Asian', size: 'XXXL', height: '151cm (4\'11.5")', weight: '59kg (130lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Fair with soft features', fullDescription: 'Tao is a very large 12-year-old boy, standing 151cm tall and weighing approximately 59kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but friendly smile. His short black hair frames his fair complexion with soft features.' }]
  },

  // INDIAN KIDS MALES
  'Indian': {
    'XS': [{ id: 'IND_KD_M_XS_001', name: 'Arjun', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'XS', height: '106cm (3\'6")', weight: '16kg (35lbs)', build: 'Petite delicate boy frame', facialFeatures: 'Sweet round face with bright dark eyes, small nose, adorable gap-toothed grin', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Arjun is a petite 6-year-old boy, standing 106cm tall and weighing approximately 16kg. He has a petite delicate boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features bright curious dark eyes, a small nose, and an adorable gap-toothed grin. His short black neat hair frames his warm brown complexion with healthy glow.' }],
    'S': [{ id: 'IND_KD_M_S_001', name: 'Ravi', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'S', height: '116cm (3\'9.5")', weight: '20kg (44lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with high cheekbones, sparkling dark eyes, small nose, mischievous smile', hairStyle: 'Short black with part', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Ravi is an active 7-year-old boy, standing 116cm tall and weighing approximately 20kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features high cheekbones, sparkling dark eyes, a small nose, and a mischievous bright smile. His short black hair with a neat part frames his medium brown complexion with warm undertones.' }],
    'M': [{ id: 'IND_KD_M_M_001', name: 'Vikram', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'M', height: '126cm (4\'1.5")', weight: '25kg (55lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, cheerful grin', hairStyle: 'Short black styled', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm tan with natural glow', fullDescription: 'Vikram is a friendly 8-year-old boy, standing 126cm tall and weighing approximately 25kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm dark eyes, a button nose, and a cheerful genuine grin. His short black styled hair frames his warm tan complexion with natural healthy glow.' }],
    'L': [{ id: 'IND_KD_M_L_001', name: 'Rahul', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'L', height: '136cm (4\'5.5")', weight: '30kg (66lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with bright eyes, broad nose, confident smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with natural radiance', fullDescription: 'Rahul is a sturdy 9-year-old boy, standing 136cm tall and weighing approximately 30kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features bright expressive eyes, a broad nose, and a confident friendly smile. His short black hair frames his dark brown complexion with natural radiance.' }],
    'XL': [{ id: 'IND_KD_M_XL_001', name: 'Anil', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'XL', height: '141cm (4\'7.5")', weight: '37kg (82lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide nose, happy grin', hairStyle: 'Short black wavy', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft features', fullDescription: 'Anil is a larger 10-year-old boy, standing 141cm tall and weighing approximately 37kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features round cheeks, small dark eyes, a wide nose, and a happy warm grin. His short black wavy hair frames his medium brown complexion with soft features.' }],
    'XXL': [{ id: 'IND_KD_M_XXL_001', name: 'Deepak', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'XXL', height: '146cm (4\'9.5")', weight: '47kg (104lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small bright eyes, large nose, gentle smile', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with soft features', fullDescription: 'Deepak is a plus size 11-year-old boy, standing 146cm tall and weighing approximately 47kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small bright eyes, a large nose, and a gentle sweet smile. His short black neat hair frames his warm brown complexion with soft features.' }],
    'XXXL': [{ id: 'IND_KD_M_XXXL_001', name: 'Sunil', age: 'Kids', sex: 'Male', ethnicity: 'Indian', size: 'XXXL', height: '151cm (4\'11.5")', weight: '58kg (128lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft texture', fullDescription: 'Sunil is a very large 12-year-old boy, standing 151cm tall and weighing approximately 58kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but friendly smile. His short black hair frames his dark brown complexion with soft texture.' }]
  },

  // SOUTHEAST ASIAN KIDS MALES
  'Southeast Asian': {
    'XS': [{ id: 'SEA_KD_M_XS_001', name: 'Minh', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'XS', height: '104cm (3\'5")', weight: '15kg (33lbs)', build: 'Petite delicate boy frame', facialFeatures: 'Sweet round face with rosy cheeks, bright dark eyes, small flat nose, adorable grin', hairStyle: 'Short black bowl cut', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Light tan with natural glow', fullDescription: 'Minh is a petite 6-year-old boy, standing 104cm tall and weighing approximately 15kg. He has a petite delicate boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features rosy cheeks, bright curious dark eyes, a small flat nose, and an adorable sweet grin. His short black bowl cut frames his light tan complexion with natural glow.' }],
    'S': [{ id: 'SEA_KD_M_S_001', name: 'Tuan', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'S', height: '114cm (3\'9")', weight: '19kg (42lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with high cheekbones, sparkling dark eyes, small nose, cheerful smile', hairStyle: 'Short black spiky', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium tan with warm undertones', fullDescription: 'Tuan is an active 7-year-old boy, standing 114cm tall and weighing approximately 19kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features high cheekbones, sparkling dark eyes, a small nose, and a cheerful bright smile. His short black spiky hair frames his medium tan complexion with warm undertones.' }],
    'M': [{ id: 'SEA_KD_M_M_001', name: 'Bao', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'M', height: '124cm (4\'1")', weight: '24kg (53lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with dimples, warm dark eyes, button nose, happy grin', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm tan with healthy glow', fullDescription: 'Bao is a friendly 8-year-old boy, standing 124cm tall and weighing approximately 24kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features adorable dimples, warm dark eyes, a button nose, and a happy genuine grin. His short black neat hair frames his warm tan complexion with healthy glow.' }],
    'L': [{ id: 'SEA_KD_M_L_001', name: 'Kiet', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'L', height: '134cm (4\'5")', weight: '29kg (64lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with bright eyes, broad nose, warm smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with natural radiance', fullDescription: 'Kiet is a sturdy 9-year-old boy, standing 134cm tall and weighing approximately 29kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features bright expressive eyes, a broad nose, and a warm friendly smile. His short black hair frames his medium brown complexion with natural radiance.' }],
    'XL': [{ id: 'SEA_KD_M_XL_001', name: 'Phong', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'XL', height: '139cm (4\'7")', weight: '36kg (79lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with round cheeks, small dark eyes, wide flat nose, happy grin', hairStyle: 'Short black wavy', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Tan with soft features', fullDescription: 'Phong is a larger 10-year-old boy, standing 139cm tall and weighing approximately 36kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features round cheeks, small dark eyes, a wide flat nose, and a happy warm grin. His short black wavy hair frames his tan complexion with soft features.' }],
    'XXL': [{ id: 'SEA_KD_M_XXL_001', name: 'Duc', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'XXL', height: '144cm (4\'9")', weight: '45kg (99lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with chubby cheeks, small dark eyes, large flat nose, gentle smile', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium tan with soft texture', fullDescription: 'Duc is a plus size 11-year-old boy, standing 144cm tall and weighing approximately 45kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features chubby cheeks, small dark eyes, a large flat nose, and a gentle sweet smile. His short black neat hair frames his medium tan complexion with soft texture.' }],
    'XXXL': [{ id: 'SEA_KD_M_XXXL_001', name: 'Hung', age: 'Kids', sex: 'Male', ethnicity: 'Southeast Asian', size: 'XXXL', height: '149cm (4\'11")', weight: '56kg (123lbs)', build: 'Very large boy frame', facialFeatures: 'Very full face with multiple chins forming, tiny dark eyes, very wide nose, shy grin', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Tan with soft features', fullDescription: 'Hung is a very large 12-year-old boy, standing 149cm tall and weighing approximately 56kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features multiple forming chins, tiny dark eyes, a very wide nose, and a shy but friendly grin. His short black hair frames his tan complexion with soft features.' }]
  },

  // INDIGENOUS KIDS MALES
  'Indigenous': {
    'XS': [{ id: 'IND_KD_M_XS_001', name: 'Chayton', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'XS', height: '107cm (3\'6")', weight: '17kg (37lbs)', build: 'Petite sturdy boy frame', facialFeatures: 'Sweet round face with high cheekbones, bright dark eyes, small nose, adorable grin', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm reddish-brown with natural glow', fullDescription: 'Chayton is a petite 6-year-old boy, standing 107cm tall and weighing approximately 17kg. He has a petite sturdy boy frame with small shoulders, thin arms, flat tummy, and slim legs. His sweet round face features high cheekbones, bright curious dark eyes, a small nose, and an adorable sweet grin. His short black hair frames his warm reddish-brown complexion with natural glow.' }],
    'S': [{ id: 'IND_KD_M_S_001', name: 'Takoda', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'S', height: '117cm (3\'10")', weight: '21kg (46lbs)', build: 'Slim active boy frame', facialFeatures: 'Oval face with prominent cheekbones, sparkling brown eyes, straight nose, mischievous smile', hairStyle: 'Medium black with headband', hairColor: 'Black', eyeColor: 'Brown', skinTone: 'Medium brown with warm undertones', fullDescription: 'Takoda is an active 7-year-old boy, standing 117cm tall and weighing approximately 21kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features prominent cheekbones, sparkling brown eyes, a straight nose, and a mischievous bright smile. His medium black hair with traditional headband frames his medium brown complexion with warm undertones.' }],
    'M': [{ id: 'IND_KD_M_M_001', name: 'Koda', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'M', height: '127cm (4\'2")', weight: '26kg (57lbs)', build: 'Average healthy boy frame', facialFeatures: 'Round friendly face with high cheekbones, warm dark eyes, broad nose, cheerful grin', hairStyle: 'Short black neat', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Warm brown with healthy glow', fullDescription: 'Koda is a friendly 8-year-old boy, standing 127cm tall and weighing approximately 26kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features high cheekbones, warm dark eyes, a broad nose, and a cheerful genuine grin. His short black neat hair frames his warm brown complexion with healthy glow.' }],
    'L': [{ id: 'IND_KD_M_L_001', name: 'Mato', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'L', height: '137cm (4\'6")', weight: '32kg (71lbs)', build: 'Sturdy well-built boy frame', facialFeatures: 'Full round face with strong cheekbones, bright dark eyes, strong nose, confident smile', hairStyle: 'Long black in ponytail', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark reddish-brown with natural radiance', fullDescription: 'Mato is a sturdy 9-year-old boy, standing 137cm tall and weighing approximately 32kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features strong cheekbones, bright dark eyes, a strong nose, and a confident friendly smile. His long black hair in a ponytail frames his dark reddish-brown complexion with natural radiance.' }],
    'XL': [{ id: 'IND_KD_M_XL_001', name: 'Ahanu', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'XL', height: '142cm (4\'8")', weight: '39kg (86lbs)', build: 'Larger husky boy frame', facialFeatures: 'Full chubby face with high cheekbones, small dark eyes, wide nose, happy grin', hairStyle: 'Medium black wavy', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Rich brown with soft features', fullDescription: 'Ahanu is a larger 10-year-old boy, standing 142cm tall and weighing approximately 39kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features high cheekbones, small dark eyes, a wide nose, and a happy warm grin. His medium black wavy hair frames his rich brown complexion with soft features.' }],
    'XXL': [{ id: 'IND_KD_M_XXL_001', name: 'Nikan', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'XXL', height: '147cm (4\'10")', weight: '49kg (108lbs)', build: 'Plus size boy frame', facialFeatures: 'Very full round face with prominent cheekbones, small bright eyes, large nose, gentle smile', hairStyle: 'Short black', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Medium brown with soft texture', fullDescription: 'Nikan is a plus size 11-year-old boy, standing 147cm tall and weighing approximately 49kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features prominent cheekbones, small bright eyes, a large nose, and a gentle friendly smile. His short black hair frames his medium brown complexion with soft texture.' }],
    'XXXL': [{ id: 'IND_KD_M_XXXL_001', name: 'Elan', age: 'Kids', sex: 'Male', ethnicity: 'Indigenous', size: 'XXXL', height: '152cm (5\'0")', weight: '61kg (134lbs)', build: 'Very large boy frame', facialFeatures: 'Very full strong face with high cheekbones, tiny dark eyes, very wide nose, shy grin', hairStyle: 'Medium black with band', hairColor: 'Black', eyeColor: 'Dark brown', skinTone: 'Dark brown with soft features', fullDescription: 'Elan is a very large 12-year-old boy, standing 152cm tall and weighing approximately 61kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full strong face features high cheekbones, tiny dark eyes, a very wide nose, and a shy but friendly grin. His medium black hair with traditional band frames his dark brown complexion with soft features.' }]
  },

  // DIVERSE KIDS MALES
  'Diverse': {
    'XS': [{ id: 'DIV_KD_M_XS_001', name: 'Kai', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'XS', height: '107cm (3\'6")', weight: '17kg (37lbs)', build: 'Petite slender boy frame with mixed heritage', facialFeatures: 'Sweet round face with unique blended features, bright hazel eyes, small nose, adorable grin', hairStyle: 'Curly brown messy', hairColor: 'Light brown with golden highlights', eyeColor: 'Hazel', skinTone: 'Warm caramel with natural glow', fullDescription: 'Kai is a petite 6-year-old boy of mixed heritage, standing 107cm tall and weighing approximately 17kg. He has a petite slender boy frame with small shoulders, thin arms, flat tummy, and skinny legs. His sweet round face features unique blended features, bright curious hazel eyes, a small nose, and an adorable sweet grin. His curly light brown hair with golden highlights in a messy style frames his warm caramel complexion with natural glow.' }],
    'S': [{ id: 'DIV_KD_M_S_001', name: 'Nico', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'S', height: '117cm (3\'10")', weight: '21kg (46lbs)', build: 'Slim active boy frame with multicultural features', facialFeatures: 'Oval face with exotic blend, sparkling amber eyes, distinctive nose, mischievous smile', hairStyle: 'Wavy dark brown', hairColor: 'Dark brown with auburn hints', eyeColor: 'Amber', skinTone: 'Golden tan with warm undertones', fullDescription: 'Nico is an active 7-year-old boy of diverse background, standing 117cm tall and weighing approximately 21kg. He has a slim active boy frame with narrow shoulders, slender arms, flat tummy, and slim legs. His oval face features an exotic blend of features, sparkling amber eyes, a distinctive nose, and a mischievous bright smile. His wavy dark brown hair with auburn hints frames his golden tan complexion with warm undertones.' }],
    'M': [{ id: 'DIV_KD_M_M_001', name: 'Elijah', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'M', height: '127cm (4\'2")', weight: '26kg (57lbs)', build: 'Average healthy boy frame with beautiful mixed features', facialFeatures: 'Round friendly face with blended heritage, warm brown-green eyes, button nose, cheerful grin', hairStyle: 'Medium curly styled', hairColor: 'Brown with natural highlights', eyeColor: 'Brown-green', skinTone: 'Warm olive with healthy glow', fullDescription: 'Elijah is a friendly 8-year-old boy of mixed ancestry, standing 127cm tall and weighing approximately 26kg. He has an average healthy boy frame with moderate shoulders, normal arms, slight tummy, and sturdy legs. His round friendly face features beautiful blended heritage, warm brown-green eyes, a button nose, and a cheerful genuine grin. His medium curly brown hair with natural highlights frames his warm olive complexion with healthy glow.' }],
    'L': [{ id: 'DIV_KD_M_L_001', name: 'Andre', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'L', height: '137cm (4\'6")', weight: '32kg (71lbs)', build: 'Sturdy well-built boy frame with multicultural presence', facialFeatures: 'Full round face with striking blend, bright golden-brown eyes, broad nose, confident smile', hairStyle: 'Short curly', hairColor: 'Dark brown with copper highlights', eyeColor: 'Golden-brown', skinTone: 'Rich olive with natural radiance', fullDescription: 'Andre is a sturdy 9-year-old boy of diverse heritage, standing 137cm tall and weighing approximately 32kg. He has a sturdy well-built boy frame with broader shoulders, solid arms, slight rounded tummy, and strong legs. His full round face features a striking blend of features, bright golden-brown eyes, a broad nose, and a confident friendly smile. His short curly dark brown hair with copper highlights frames his rich olive complexion with natural radiance.' }],
    'XL': [{ id: 'DIV_KD_M_XL_001', name: 'Isaiah', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'XL', height: '142cm (4\'8")', weight: '40kg (88lbs)', build: 'Larger husky boy frame with unique heritage blend', facialFeatures: 'Full chubby face with exotic features, small warm eyes, wide nose, happy grin', hairStyle: 'Medium curly waves', hairColor: 'Dark with golden streaks', eyeColor: 'Warm brown', skinTone: 'Warm bronze with soft features', fullDescription: 'Isaiah is a larger 10-year-old boy of mixed heritage, standing 142cm tall and weighing approximately 40kg. He has a larger husky boy frame with wide shoulders, thick arms, rounded belly, and thick legs. His full chubby face features exotic blend of features, small warm eyes, a wide nose, and a happy infectious grin. His medium curly dark hair with golden streaks frames his warm bronze complexion with soft features.' }],
    'XXL': [{ id: 'DIV_KD_M_XXL_001', name: 'Gabriel', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'XXL', height: '147cm (4\'10")', weight: '50kg (110lbs)', build: 'Plus size boy frame with beautiful multicultural features', facialFeatures: 'Very full round face with complex heritage, small bright eyes, large nose, gentle smile', hairStyle: 'Short wavy', hairColor: 'Brown with highlights', eyeColor: 'Brown', skinTone: 'Medium tan with soft texture', fullDescription: 'Gabriel is a plus size 11-year-old boy of diverse ancestry, standing 147cm tall and weighing approximately 50kg. He has a plus size boy frame with very wide shoulders, heavy arms, large rounded belly, and thick sturdy legs. His very full round face features complex heritage blend, small bright eyes, a large nose, and a gentle friendly smile. His short wavy brown hair with highlights frames his medium tan complexion with soft texture.' }],
    'XXXL': [{ id: 'DIV_KD_M_XXXL_001', name: 'Daniel', age: 'Kids', sex: 'Male', ethnicity: 'Diverse', size: 'XXXL', height: '152cm (5\'0")', weight: '62kg (137lbs)', build: 'Very large boy frame with beautiful blended heritage', facialFeatures: 'Very full face with unique mixed features, tiny bright eyes, very wide nose, shy warm grin', hairStyle: 'Medium curly', hairColor: 'Dark brown with golden highlights', eyeColor: 'Brown-hazel', skinTone: 'Warm caramel with soft features', fullDescription: 'Daniel is a very large 12-year-old boy of mixed heritage, standing 152cm tall and weighing approximately 62kg. He has a very large boy frame with extremely wide shoulders, very heavy arms, very large belly, and very thick legs. His very full face features unique blended features, tiny bright eyes, a very wide nose, and a shy but warm grin. His medium curly dark brown hair with golden highlights frames his warm caramel complexion with soft features.' }]
  }
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getKidsPersona(ethnicity: Ethnicity, sex: 'Female' | 'Male', size: Size): Persona | undefined {
  const collection = sex === 'Female' ? KIDS_FEMALE_PERSONAS : KIDS_MALE_PERSONAS;
  return collection[ethnicity]?.[size]?.[0];
}

export function hasKidsPersona(ethnicity: Ethnicity, sex: 'Female' | 'Male', size: Size): boolean {
  return getKidsPersona(ethnicity, sex, size) !== undefined;
}

export function getAllKidsPersonas(): Persona[] {
  const all: Persona[] = [];
  const ethnicities: Ethnicity[] = ['White', 'Black', 'Hispanic', 'Asian', 'Indian', 'Southeast Asian', 'Indigenous', 'Diverse'];
  const sizes: Size[] = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'];
  
  for (const ethnicity of ethnicities) {
    for (const size of sizes) {
      const female = getKidsPersona(ethnicity, 'Female', size);
      const male = getKidsPersona(ethnicity, 'Male', size);
      if (female) all.push(female);
      if (male) all.push(male);
    }
  }
  return all;
}

export const KIDS_PERSONAS = {
  female: KIDS_FEMALE_PERSONAS,
  male: KIDS_MALE_PERSONAS
};
