/**
 * ============================================================================
 * TEEN PERSONAS - MISSING 82 PERSONAS
 * Age Range: 13-17 years
 * ============================================================================
 */

export const missingTeenPersonas = [
  // ============================================================================
  // WHITE FEMALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "WHT_TN_F_XS_001",
    name: "Emma",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "White",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Youthful features, bright blue eyes, clear skin",
    hairStyle: "Long trendy style",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Emma is a 13-year-old teen female of White heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows youthful features, bright blue eyes, and clear skin. She has long trendy style light brown hair and blue eyes. Her fair with youthful glow skin is clear and youthful. Emma has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_F_M_001",
    name: "Olivia",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "White",
    size: "M",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Average teen frame",
    facialFeatures: "Youthful features, bright blue eyes, clear skin",
    hairStyle: "Long trendy style",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Olivia is a 15-year-old teen female of White heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has an average teen frame with developing teen proportions. Her face shows youthful features, bright blue eyes, and clear skin. She has long trendy style light brown hair and blue eyes. Her fair with youthful glow skin is clear and youthful. Olivia has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_F_L_001",
    name: "Sophia",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "White",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful features, bright blue eyes, clear skin",
    hairStyle: "Long trendy style",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Sophia is a 16-year-old teen female of White heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows youthful features, bright blue eyes, and clear skin. She has long trendy style light brown hair and blue eyes. Her fair with youthful glow skin is clear and youthful. Sophia has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_F_XL_001",
    name: "Ava",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "White",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Youthful features, bright blue eyes, clear skin",
    hairStyle: "Long trendy style",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Ava is a 17-year-old teen female of White heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows youthful features, bright blue eyes, and clear skin. She has long trendy style light brown hair and blue eyes. Her fair with youthful glow skin is clear and youthful. Ava has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_F_2XL_001",
    name: "Isabella",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "White",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Youthful features, bright blue eyes, clear skin",
    hairStyle: "Long trendy style",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Isabella is a 17-year-old teen female of White heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows youthful features, bright blue eyes, and clear skin. She has long trendy style light brown hair and blue eyes. Her fair with youthful glow skin is clear and youthful. Isabella has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // WHITE MALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "WHT_TN_M_XS_001",
    name: "Ethan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "White",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Youthful features, developing jawline, bright blue eyes",
    hairStyle: "Short trendy cut",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Ethan is a 13-year-old teen male of White heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows youthful features, developing jawline, and bright blue eyes. He has short trendy cut light brown hair and blue eyes. His fair with youthful glow skin is clear and youthful. Ethan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_M_M_001",
    name: "Liam",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "White",
    size: "M",
    height: "170cm (5'7\")",
    weight: "61kg (134lbs)",
    build: "Average teen frame",
    facialFeatures: "Youthful features, developing jawline, bright blue eyes",
    hairStyle: "Short trendy cut",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Liam is a 15-year-old teen male of White heritage, standing 170cm (5'7\") tall and weighing approximately 61kg (134lbs). He has an average teen frame with developing teen proportions. His face shows youthful features, developing jawline, and bright blue eyes. He has short trendy cut light brown hair and blue eyes. His fair with youthful glow skin is clear and youthful. Liam has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_M_L_001",
    name: "Noah",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "White",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful features, developing jawline, bright blue eyes",
    hairStyle: "Short trendy cut",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Noah is a 16-year-old teen male of White heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows youthful features, developing jawline, and bright blue eyes. He has short trendy cut light brown hair and blue eyes. His fair with youthful glow skin is clear and youthful. Noah has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_M_XL_001",
    name: "Mason",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "White",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Youthful features, developing jawline, bright blue eyes",
    hairStyle: "Short trendy cut",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Mason is a 17-year-old teen male of White heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows youthful features, developing jawline, and bright blue eyes. He has short trendy cut light brown hair and blue eyes. His fair with youthful glow skin is clear and youthful. Mason has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_TN_M_2XL_001",
    name: "Lucas",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "White",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Youthful features, developing jawline, bright blue eyes",
    hairStyle: "Short trendy cut",
    hairColor: "Light brown",
    eyeColor: "Blue",
    skinTone: "Fair with youthful glow",
    fullDescription: "Lucas is a 17-year-old teen male of White heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows youthful features, developing jawline, and bright blue eyes. He has short trendy cut light brown hair and blue eyes. His fair with youthful glow skin is clear and youthful. Lucas has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK FEMALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "BLK_TN_F_XS_001",
    name: "Aaliyah",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Black",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Aaliyah is a 13-year-old teen female of Black heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with youthful glow skin is clear and youthful. Aaliyah has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_F_M_001",
    name: "Imani",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Black",
    size: "M",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Average teen frame",
    facialFeatures: "Youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Imani is a 15-year-old teen female of Black heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has an average teen frame with developing teen proportions. Her face shows youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with youthful glow skin is clear and youthful. Imani has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_F_L_001",
    name: "Zara",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Black",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Zara is a 16-year-old teen female of Black heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with youthful glow skin is clear and youthful. Zara has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_F_XL_001",
    name: "Nia",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Black",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Nia is a 17-year-old teen female of Black heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with youthful glow skin is clear and youthful. Nia has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_F_2XL_001",
    name: "Destiny",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Black",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Destiny is a 17-year-old teen female of Black heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with youthful glow skin is clear and youthful. Destiny has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "BLK_TN_M_XS_001",
    name: "Jordan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Black",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Youthful features, strong emerging features, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Jordan is a 13-year-old teen male of Black heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows youthful features, strong emerging features, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with youthful glow skin is clear and youthful. Jordan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_M_S_001",
    name: "Jayden",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Black",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "Youthful features, strong emerging features, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Jayden is a 14-year-old teen male of Black heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows youthful features, strong emerging features, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with youthful glow skin is clear and youthful. Jayden has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_M_L_001",
    name: "Malik",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Black",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful features, strong emerging features, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Malik is a 16-year-old teen male of Black heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows youthful features, strong emerging features, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with youthful glow skin is clear and youthful. Malik has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_M_XL_001",
    name: "Darius",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Black",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Youthful features, strong emerging features, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Darius is a 17-year-old teen male of Black heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows youthful features, strong emerging features, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with youthful glow skin is clear and youthful. Darius has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_TN_M_2XL_001",
    name: "Xavier",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Black",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Youthful features, strong emerging features, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with youthful glow",
    fullDescription: "Xavier is a 17-year-old teen male of Black heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows youthful features, strong emerging features, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with youthful glow skin is clear and youthful. Xavier has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "HSP_TN_F_XS_001",
    name: "Sofia",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Warm youthful glow, expressive eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Sofia is a 13-year-old teen female of Hispanic heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows warm youthful glow, expressive eyes, and soft features. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with youthful glow skin is clear and youthful. Sofia has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_F_S_001",
    name: "Valentina",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "S",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Slim teen frame",
    facialFeatures: "Warm youthful glow, expressive eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Valentina is a 14-year-old teen female of Hispanic heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a slim teen frame with developing teen proportions. Her face shows warm youthful glow, expressive eyes, and soft features. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with youthful glow skin is clear and youthful. Valentina has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_F_L_001",
    name: "Camila",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Warm youthful glow, expressive eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Camila is a 16-year-old teen female of Hispanic heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows warm youthful glow, expressive eyes, and soft features. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with youthful glow skin is clear and youthful. Camila has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_F_XL_001",
    name: "Luna",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Warm youthful glow, expressive eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Luna is a 17-year-old teen female of Hispanic heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows warm youthful glow, expressive eyes, and soft features. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with youthful glow skin is clear and youthful. Luna has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_F_2XL_001",
    name: "Mariana",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Warm youthful glow, expressive eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Mariana is a 17-year-old teen female of Hispanic heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows warm youthful glow, expressive eyes, and soft features. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with youthful glow skin is clear and youthful. Mariana has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "HSP_TN_M_XS_001",
    name: "Diego",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Youthful warmth, developing features, warm brown eyes",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Diego is a 13-year-old teen male of Hispanic heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows youthful warmth, developing features, and warm brown eyes. He has short styled cut dark brown hair and warm brown eyes. His warm olive with youthful glow skin is clear and youthful. Diego has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_M_S_001",
    name: "Mateo",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "Youthful warmth, developing features, warm brown eyes",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Mateo is a 14-year-old teen male of Hispanic heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows youthful warmth, developing features, and warm brown eyes. He has short styled cut dark brown hair and warm brown eyes. His warm olive with youthful glow skin is clear and youthful. Mateo has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_M_L_001",
    name: "Santiago",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful warmth, developing features, warm brown eyes",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Santiago is a 16-year-old teen male of Hispanic heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows youthful warmth, developing features, and warm brown eyes. He has short styled cut dark brown hair and warm brown eyes. His warm olive with youthful glow skin is clear and youthful. Santiago has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_M_XL_001",
    name: "Sebastian",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Youthful warmth, developing features, warm brown eyes",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Sebastian is a 17-year-old teen male of Hispanic heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows youthful warmth, developing features, and warm brown eyes. He has short styled cut dark brown hair and warm brown eyes. His warm olive with youthful glow skin is clear and youthful. Sebastian has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_TN_M_2XL_001",
    name: "Adrian",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Youthful warmth, developing features, warm brown eyes",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with youthful glow",
    fullDescription: "Adrian is a 17-year-old teen male of Hispanic heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows youthful warmth, developing features, and warm brown eyes. He has short styled cut dark brown hair and warm brown eyes. His warm olive with youthful glow skin is clear and youthful. Adrian has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "ASN_TN_F_XS_001",
    name: "Mei",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Asian",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Delicate youthful features, almond eyes, clear skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Mei is a 13-year-old teen female of Asian heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows delicate youthful features, almond eyes, and clear skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is clear and youthful. Mei has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_F_S_001",
    name: "Sakura",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Asian",
    size: "S",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Slim teen frame",
    facialFeatures: "Delicate youthful features, almond eyes, clear skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Sakura is a 14-year-old teen female of Asian heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a slim teen frame with developing teen proportions. Her face shows delicate youthful features, almond eyes, and clear skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is clear and youthful. Sakura has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_F_L_001",
    name: "Yuki",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Asian",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Delicate youthful features, almond eyes, clear skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Yuki is a 16-year-old teen female of Asian heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows delicate youthful features, almond eyes, and clear skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is clear and youthful. Yuki has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_F_XL_001",
    name: "Hana",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Asian",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Delicate youthful features, almond eyes, clear skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Hana is a 17-year-old teen female of Asian heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows delicate youthful features, almond eyes, and clear skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is clear and youthful. Hana has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_F_2XL_001",
    name: "Lily",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Asian",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Delicate youthful features, almond eyes, clear skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Lily is a 17-year-old teen female of Asian heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows delicate youthful features, almond eyes, and clear skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is clear and youthful. Lily has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN MALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "ASN_TN_M_XS_001",
    name: "Kai",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Asian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Clean youthful features, almond eyes, smooth skin",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Kai is a 13-year-old teen male of Asian heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows clean youthful features, almond eyes, and smooth skin. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is clear and youthful. Kai has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_M_M_001",
    name: "Ryu",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Asian",
    size: "M",
    height: "170cm (5'7\")",
    weight: "61kg (134lbs)",
    build: "Average teen frame",
    facialFeatures: "Clean youthful features, almond eyes, smooth skin",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Ryu is a 15-year-old teen male of Asian heritage, standing 170cm (5'7\") tall and weighing approximately 61kg (134lbs). He has an average teen frame with developing teen proportions. His face shows clean youthful features, almond eyes, and smooth skin. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is clear and youthful. Ryu has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_M_L_001",
    name: "Jin",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Asian",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Clean youthful features, almond eyes, smooth skin",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Jin is a 16-year-old teen male of Asian heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows clean youthful features, almond eyes, and smooth skin. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is clear and youthful. Jin has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_M_XL_001",
    name: "Hiro",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Asian",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Clean youthful features, almond eyes, smooth skin",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Hiro is a 17-year-old teen male of Asian heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows clean youthful features, almond eyes, and smooth skin. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is clear and youthful. Hiro has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_TN_M_2XL_001",
    name: "Tao",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Asian",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Clean youthful features, almond eyes, smooth skin",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Tao is a 17-year-old teen male of Asian heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows clean youthful features, almond eyes, and smooth skin. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is clear and youthful. Tao has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "IND_TN_F_XS_001",
    name: "Aanya",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indian",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Youthful glow, expressive dark eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Aanya is a 13-year-old teen female of Indian heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows youthful glow, expressive dark eyes, and soft features. She has long flowing style black hair and dark brown eyes. Her warm brown with youthful glow skin is clear and youthful. Aanya has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_F_S_001",
    name: "Ishita",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indian",
    size: "S",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Slim teen frame",
    facialFeatures: "Youthful glow, expressive dark eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Ishita is a 14-year-old teen female of Indian heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a slim teen frame with developing teen proportions. Her face shows youthful glow, expressive dark eyes, and soft features. She has long flowing style black hair and dark brown eyes. Her warm brown with youthful glow skin is clear and youthful. Ishita has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_F_L_001",
    name: "Kavya",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indian",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful glow, expressive dark eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Kavya is a 16-year-old teen female of Indian heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows youthful glow, expressive dark eyes, and soft features. She has long flowing style black hair and dark brown eyes. Her warm brown with youthful glow skin is clear and youthful. Kavya has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_F_XL_001",
    name: "Riya",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indian",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Youthful glow, expressive dark eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Riya is a 17-year-old teen female of Indian heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows youthful glow, expressive dark eyes, and soft features. She has long flowing style black hair and dark brown eyes. Her warm brown with youthful glow skin is clear and youthful. Riya has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_F_2XL_001",
    name: "Saanvi",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indian",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Youthful glow, expressive dark eyes, soft features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Saanvi is a 17-year-old teen female of Indian heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows youthful glow, expressive dark eyes, and soft features. She has long flowing style black hair and dark brown eyes. Her warm brown with youthful glow skin is clear and youthful. Saanvi has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "IND_TN_M_XS_001",
    name: "Arjun",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Youthful features, expressive eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Arjun is a 13-year-old teen male of Indian heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows youthful features, expressive eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His warm brown with youthful glow skin is clear and youthful. Arjun has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_M_S_001",
    name: "Dev",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indian",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "Youthful features, expressive eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Dev is a 14-year-old teen male of Indian heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows youthful features, expressive eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His warm brown with youthful glow skin is clear and youthful. Dev has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_M_L_001",
    name: "Rohan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indian",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful features, expressive eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Rohan is a 16-year-old teen male of Indian heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows youthful features, expressive eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His warm brown with youthful glow skin is clear and youthful. Rohan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_M_XL_001",
    name: "Aditya",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indian",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Youthful features, expressive eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Aditya is a 17-year-old teen male of Indian heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows youthful features, expressive eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His warm brown with youthful glow skin is clear and youthful. Aditya has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_TN_M_2XL_001",
    name: "Vivaan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indian",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Youthful features, expressive eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with youthful glow",
    fullDescription: "Vivaan is a 17-year-old teen male of Indian heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows youthful features, expressive eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His warm brown with youthful glow skin is clear and youthful. Vivaan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN FEMALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "SEA_TN_F_XS_001",
    name: "Mai",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Soft youthful features, warm eyes, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Mai is a 13-year-old teen female of Southeast Asian heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows soft youthful features, warm eyes, and gentle smile. She has long straight style black hair and dark brown eyes. Her light tan with youthful glow skin is clear and youthful. Mai has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_F_M_001",
    name: "Linh",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "M",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Average teen frame",
    facialFeatures: "Soft youthful features, warm eyes, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Linh is a 15-year-old teen female of Southeast Asian heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has an average teen frame with developing teen proportions. Her face shows soft youthful features, warm eyes, and gentle smile. She has long straight style black hair and dark brown eyes. Her light tan with youthful glow skin is clear and youthful. Linh has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_F_L_001",
    name: "Thuy",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Soft youthful features, warm eyes, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Thuy is a 16-year-old teen female of Southeast Asian heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows soft youthful features, warm eyes, and gentle smile. She has long straight style black hair and dark brown eyes. Her light tan with youthful glow skin is clear and youthful. Thuy has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_F_XL_001",
    name: "Anh",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Soft youthful features, warm eyes, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Anh is a 17-year-old teen female of Southeast Asian heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows soft youthful features, warm eyes, and gentle smile. She has long straight style black hair and dark brown eyes. Her light tan with youthful glow skin is clear and youthful. Anh has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_F_2XL_001",
    name: "Dara",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Soft youthful features, warm eyes, gentle smile",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Dara is a 17-year-old teen female of Southeast Asian heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows soft youthful features, warm eyes, and gentle smile. She has long straight style black hair and dark brown eyes. Her light tan with youthful glow skin is clear and youthful. Dara has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN MALE - ALL 6 SIZES MISSING
  // ============================================================================
  {
    id: "SEA_TN_M_XS_001",
    name: "Lian",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Lian is a 13-year-old teen male of Southeast Asian heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Lian has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_M_S_001",
    name: "Minh",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Minh is a 14-year-old teen male of Southeast Asian heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Minh has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_M_M_001",
    name: "Thanh",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "M",
    height: "170cm (5'7\")",
    weight: "61kg (134lbs)",
    build: "Average teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Thanh is a 15-year-old teen male of Southeast Asian heritage, standing 170cm (5'7\") tall and weighing approximately 61kg (134lbs). He has an average teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Thanh has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_M_L_001",
    name: "Phan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Phan is a 16-year-old teen male of Southeast Asian heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Phan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_M_XL_001",
    name: "Bao",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Bao is a 17-year-old teen male of Southeast Asian heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Bao has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_TN_M_2XL_001",
    name: "Duc",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Youthful warm features, friendly eyes, developing frame",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with youthful glow",
    fullDescription: "Duc is a 17-year-old teen male of Southeast Asian heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows youthful warm features, friendly eyes, and developing frame. He has short styled cut black hair and dark brown eyes. His light tan with youthful glow skin is clear and youthful. Duc has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "MDE_TN_F_XS_001",
    name: "Leila",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "Striking dark eyes, youthful glow, elegant features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Leila is a 13-year-old teen female of Middle Eastern heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows striking dark eyes, youthful glow, and elegant features. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm youthful glow skin is clear and youthful. Leila has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_F_S_001",
    name: "Mariam",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Slim teen frame",
    facialFeatures: "Striking dark eyes, youthful glow, elegant features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Mariam is a 14-year-old teen female of Middle Eastern heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a slim teen frame with developing teen proportions. Her face shows striking dark eyes, youthful glow, and elegant features. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm youthful glow skin is clear and youthful. Mariam has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_F_L_001",
    name: "Sara",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Striking dark eyes, youthful glow, elegant features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Sara is a 16-year-old teen female of Middle Eastern heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows striking dark eyes, youthful glow, and elegant features. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm youthful glow skin is clear and youthful. Sara has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_F_XL_001",
    name: "Noor",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "Striking dark eyes, youthful glow, elegant features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Noor is a 17-year-old teen female of Middle Eastern heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows striking dark eyes, youthful glow, and elegant features. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm youthful glow skin is clear and youthful. Noor has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_F_2XL_001",
    name: "Hana",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "Striking dark eyes, youthful glow, elegant features",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Hana is a 17-year-old teen female of Middle Eastern heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows striking dark eyes, youthful glow, and elegant features. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm youthful glow skin is clear and youthful. Hana has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "MDE_TN_M_XS_001",
    name: "Adam",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "Developing strong features, dark expressive eyes, youthful presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Adam is a 13-year-old teen male of Middle Eastern heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows developing strong features, dark expressive eyes, and youthful presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm youthful glow skin is clear and youthful. Adam has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_M_S_001",
    name: "Zaid",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "Developing strong features, dark expressive eyes, youthful presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Zaid is a 14-year-old teen male of Middle Eastern heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows developing strong features, dark expressive eyes, and youthful presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm youthful glow skin is clear and youthful. Zaid has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_M_L_001",
    name: "Karim",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "Developing strong features, dark expressive eyes, youthful presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Karim is a 16-year-old teen male of Middle Eastern heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows developing strong features, dark expressive eyes, and youthful presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm youthful glow skin is clear and youthful. Karim has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_M_XL_001",
    name: "Amir",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "Developing strong features, dark expressive eyes, youthful presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Amir is a 17-year-old teen male of Middle Eastern heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows developing strong features, dark expressive eyes, and youthful presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm youthful glow skin is clear and youthful. Amir has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_TN_M_2XL_001",
    name: "Faisal",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "Developing strong features, dark expressive eyes, youthful presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm youthful glow",
    fullDescription: "Faisal is a 17-year-old teen male of Middle Eastern heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows developing strong features, dark expressive eyes, and youthful presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm youthful glow skin is clear and youthful. Faisal has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS FEMALE - ALL 6 SIZES MISSING
  // ============================================================================
  {
    id: "IDG_TN_F_XS_001",
    name: "Kaya",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "XS",
    height: "150cm (4'11\")",
    weight: "42kg (93lbs)",
    build: "Petite teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Kaya is a 13-year-old teen female of Indigenous heritage, standing 150cm (4'11\") tall and weighing approximately 42kg (93lbs). She has a petite teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Kaya has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_F_S_001",
    name: "Nova",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "S",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Slim teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Nova is a 14-year-old teen female of Indigenous heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a slim teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Nova has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_F_M_001",
    name: "Aiyana",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "M",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Average teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Aiyana is a 15-year-old teen female of Indigenous heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has an average teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Aiyana has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_F_L_001",
    name: "Winona",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "L",
    height: "165cm (5'5\")",
    weight: "62kg (137lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Winona is a 16-year-old teen female of Indigenous heritage, standing 165cm (5'5\") tall and weighing approximately 62kg (137lbs). She has a sturdy teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Winona has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_F_XL_001",
    name: "Dakota",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "XL",
    height: "168cm (5'6\")",
    weight: "72kg (159lbs)",
    build: "Large teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Dakota is a 17-year-old teen female of Indigenous heritage, standing 168cm (5'6\") tall and weighing approximately 72kg (159lbs). She has a large teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Dakota has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_F_2XL_001",
    name: "Chenoa",
    age: "Teen",
    ageRange: "13-17",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "170cm (5'7\")",
    weight: "82kg (181lbs)",
    build: "Plus size teen frame",
    facialFeatures: "High cheekbones, youthful strength, natural beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Chenoa is a 17-year-old teen female of Indigenous heritage, standing 170cm (5'7\") tall and weighing approximately 82kg (181lbs). She has a plus size teen frame with developing teen proportions. Her face shows high cheekbones, youthful strength, and natural beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is clear and youthful. Chenoa has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "IDG_TN_M_XS_001",
    name: "Takoda",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "45kg (99lbs)",
    build: "Slim lanky teen frame",
    facialFeatures: "High cheekbones, developing strong features, proud bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Takoda is a 13-year-old teen male of Indigenous heritage, standing 155cm (5'1\") tall and weighing approximately 45kg (99lbs). He has a slim lanky teen frame with developing teen proportions. His face shows high cheekbones, developing strong features, and proud bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is clear and youthful. Takoda has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_M_S_001",
    name: "Koda",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "S",
    height: "163cm (5'4\")",
    weight: "52kg (115lbs)",
    build: "Slim athletic teen frame",
    facialFeatures: "High cheekbones, developing strong features, proud bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Koda is a 14-year-old teen male of Indigenous heritage, standing 163cm (5'4\") tall and weighing approximately 52kg (115lbs). He has a slim athletic teen frame with developing teen proportions. His face shows high cheekbones, developing strong features, and proud bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is clear and youthful. Koda has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_M_L_001",
    name: "Chayton",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "L",
    height: "175cm (5'9\")",
    weight: "70kg (154lbs)",
    build: "Sturdy teen frame",
    facialFeatures: "High cheekbones, developing strong features, proud bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Chayton is a 16-year-old teen male of Indigenous heritage, standing 175cm (5'9\") tall and weighing approximately 70kg (154lbs). He has a sturdy teen frame with developing teen proportions. His face shows high cheekbones, developing strong features, and proud bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is clear and youthful. Chayton has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_M_XL_001",
    name: "Elan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "XL",
    height: "180cm (5'11\")",
    weight: "82kg (181lbs)",
    build: "Large athletic teen frame",
    facialFeatures: "High cheekbones, developing strong features, proud bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Elan is a 17-year-old teen male of Indigenous heritage, standing 180cm (5'11\") tall and weighing approximately 82kg (181lbs). He has a large athletic teen frame with developing teen proportions. His face shows high cheekbones, developing strong features, and proud bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is clear and youthful. Elan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_TN_M_2XL_001",
    name: "Nikan",
    age: "Teen",
    ageRange: "13-17",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "183cm (6'0\")",
    weight: "95kg (209lbs)",
    build: "Very large teen frame",
    facialFeatures: "High cheekbones, developing strong features, proud bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Nikan is a 17-year-old teen male of Indigenous heritage, standing 183cm (6'0\") tall and weighing approximately 95kg (209lbs). He has a very large teen frame with developing teen proportions. His face shows high cheekbones, developing strong features, and proud bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is clear and youthful. Nikan has an energetic teen presence.",
    version: "2.0",
    createdDate: "2025-12-28"
  }
];

// Total: 82 Teen Personas
export default missingTeenPersonas;
