/**
 * ============================================================================
 * YOUNG ADULT PERSONAS - MISSING 78 PERSONAS
 * Age Range: 18-24 years
 * ============================================================================
 */

export const missingYoungAdultPersonas = [
  // ============================================================================
  // WHITE FEMALE - Missing: XS, M, XL, 2XL (4)
  // ============================================================================
  {
    id: "WHT_YA_F_XS_001",
    name: "Ashley",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "White",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Fresh youthful features, bright eyes, clear complexion",
    hairStyle: "Long flowing contemporary style",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Ashley is an 18-year-old young adult female of White heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows fresh youthful features, bright eyes, and clear complexion. She has long flowing contemporary style light brown hair and blue-green eyes. Her fair with fresh glow skin is fresh and vibrant. Ashley exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_F_M_001",
    name: "Brittany",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "White",
    size: "M",
    height: "165cm (5'5\")",
    weight: "61kg (134lbs)",
    build: "Average athletic frame",
    facialFeatures: "Fresh youthful features, bright eyes, clear complexion",
    hairStyle: "Long flowing contemporary style",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Brittany is a 20-year-old young adult female of White heritage, standing 165cm (5'5\") tall and weighing approximately 61kg (134lbs). She has an average athletic frame with youthful proportions. Her face shows fresh youthful features, bright eyes, and clear complexion. She has long flowing contemporary style light brown hair and blue-green eyes. Her fair with fresh glow skin is fresh and vibrant. Brittany exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_F_XL_001",
    name: "Jessica",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "White",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Fresh youthful features, bright eyes, clear complexion",
    hairStyle: "Long flowing contemporary style",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Jessica is a 22-year-old young adult female of White heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows fresh youthful features, bright eyes, and clear complexion. She has long flowing contemporary style light brown hair and blue-green eyes. Her fair with fresh glow skin is fresh and vibrant. Jessica exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_F_2XL_001",
    name: "Stephanie",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "White",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Fresh youthful features, bright eyes, clear complexion",
    hairStyle: "Long flowing contemporary style",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Stephanie is a 23-year-old young adult female of White heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows fresh youthful features, bright eyes, and clear complexion. She has long flowing contemporary style light brown hair and blue-green eyes. Her fair with fresh glow skin is fresh and vibrant. Stephanie exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // WHITE MALE - Missing: XS, M, XL, 2XL (4)
  // ============================================================================
  {
    id: "WHT_YA_M_XS_001",
    name: "Brandon",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "White",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Young defined features, bright eyes, clean jawline",
    hairStyle: "Short modern styled",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Brandon is an 18-year-old young adult male of White heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows young defined features, bright eyes, and clean jawline. He has short modern styled light brown hair and blue-green eyes. His fair with fresh glow skin is fresh and vibrant. Brandon exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_M_M_001",
    name: "Tyler",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "White",
    size: "M",
    height: "175cm (5'9\")",
    weight: "75kg (165lbs)",
    build: "Average athletic frame",
    facialFeatures: "Young defined features, bright eyes, clean jawline",
    hairStyle: "Short modern styled",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Tyler is a 20-year-old young adult male of White heritage, standing 175cm (5'9\") tall and weighing approximately 75kg (165lbs). He has an average athletic frame with youthful proportions. His face shows young defined features, bright eyes, and clean jawline. He has short modern styled light brown hair and blue-green eyes. His fair with fresh glow skin is fresh and vibrant. Tyler exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_M_XL_001",
    name: "Ryan",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "White",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Young defined features, bright eyes, clean jawline",
    hairStyle: "Short modern styled",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Ryan is a 22-year-old young adult male of White heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows young defined features, bright eyes, and clean jawline. He has short modern styled light brown hair and blue-green eyes. His fair with fresh glow skin is fresh and vibrant. Ryan exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "WHT_YA_M_2XL_001",
    name: "Justin",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "White",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Young defined features, bright eyes, clean jawline",
    hairStyle: "Short modern styled",
    hairColor: "Light brown",
    eyeColor: "Blue-green",
    skinTone: "Fair with fresh glow",
    fullDescription: "Justin is a 23-year-old young adult male of White heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows young defined features, bright eyes, and clean jawline. He has short modern styled light brown hair and blue-green eyes. His fair with fresh glow skin is fresh and vibrant. Justin exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK FEMALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "BLK_YA_F_XS_001",
    name: "Brianna",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Black",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Vibrant youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Brianna is an 18-year-old young adult female of Black heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows vibrant youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with vibrant glow skin is fresh and vibrant. Brianna exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_F_M_001",
    name: "Kiara",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Black",
    size: "M",
    height: "165cm (5'5\")",
    weight: "61kg (134lbs)",
    build: "Average athletic frame",
    facialFeatures: "Vibrant youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Kiara is a 20-year-old young adult female of Black heritage, standing 165cm (5'5\") tall and weighing approximately 61kg (134lbs). She has an average athletic frame with youthful proportions. Her face shows vibrant youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with vibrant glow skin is fresh and vibrant. Kiara exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_F_L_001",
    name: "Jazmine",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Black",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Vibrant youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Jazmine is a 21-year-old young adult female of Black heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows vibrant youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with vibrant glow skin is fresh and vibrant. Jazmine exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_F_XL_001",
    name: "Alicia",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Black",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Vibrant youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Alicia is a 22-year-old young adult female of Black heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows vibrant youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with vibrant glow skin is fresh and vibrant. Alicia exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_F_2XL_001",
    name: "Shayla",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Black",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Vibrant youthful glow, full lips, bright expressive eyes",
    hairStyle: "Natural curls styled",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Shayla is a 23-year-old young adult female of Black heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows vibrant youthful glow, full lips, and bright expressive eyes. She has natural curls styled black hair and dark brown eyes. Her rich brown with vibrant glow skin is fresh and vibrant. Shayla exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // BLACK MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "BLK_YA_M_XS_001",
    name: "DeShawn",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Black",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong young features, confident expression, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "DeShawn is an 18-year-old young adult male of Black heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows strong young features, confident expression, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with vibrant glow skin is fresh and vibrant. DeShawn exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_M_S_001",
    name: "Tyrell",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Black",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong young features, confident expression, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Tyrell is a 19-year-old young adult male of Black heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows strong young features, confident expression, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with vibrant glow skin is fresh and vibrant. Tyrell exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_M_L_001",
    name: "Marquis",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Black",
    size: "L",
    height: "180cm (5'11\")",
    weight: "86kg (190lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Strong young features, confident expression, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Marquis is a 21-year-old young adult male of Black heritage, standing 180cm (5'11\") tall and weighing approximately 86kg (190lbs). He has a sturdy muscular frame with youthful proportions. His face shows strong young features, confident expression, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with vibrant glow skin is fresh and vibrant. Marquis exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_M_XL_001",
    name: "Rashad",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Black",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Strong young features, confident expression, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Rashad is a 22-year-old young adult male of Black heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows strong young features, confident expression, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with vibrant glow skin is fresh and vibrant. Rashad exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "BLK_YA_M_2XL_001",
    name: "Jalen",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Black",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Strong young features, confident expression, bright eyes",
    hairStyle: "Short fade cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Rich brown with vibrant glow",
    fullDescription: "Jalen is a 23-year-old young adult male of Black heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows strong young features, confident expression, and bright eyes. He has short fade cut black hair and dark brown eyes. His rich brown with vibrant glow skin is fresh and vibrant. Jalen exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "HSP_YA_F_XS_001",
    name: "Daniela",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Fresh warm glow, expressive eyes, youthful beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Daniela is an 18-year-old young adult female of Hispanic heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows fresh warm glow, expressive eyes, and youthful beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with fresh glow skin is fresh and vibrant. Daniela exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_F_S_001",
    name: "Alejandra",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "S",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Fresh warm glow, expressive eyes, youthful beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Alejandra is a 19-year-old young adult female of Hispanic heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has a slim athletic frame with youthful proportions. Her face shows fresh warm glow, expressive eyes, and youthful beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with fresh glow skin is fresh and vibrant. Alejandra exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_F_L_001",
    name: "Valeria",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Fresh warm glow, expressive eyes, youthful beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Valeria is a 21-year-old young adult female of Hispanic heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows fresh warm glow, expressive eyes, and youthful beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with fresh glow skin is fresh and vibrant. Valeria exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_F_XL_001",
    name: "Fernanda",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Fresh warm glow, expressive eyes, youthful beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Fernanda is a 22-year-old young adult female of Hispanic heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows fresh warm glow, expressive eyes, and youthful beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with fresh glow skin is fresh and vibrant. Fernanda exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_F_2XL_001",
    name: "Andrea",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Fresh warm glow, expressive eyes, youthful beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Andrea is a 23-year-old young adult female of Hispanic heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows fresh warm glow, expressive eyes, and youthful beauty. She has long flowing style dark brown hair and warm brown eyes. Her warm olive with fresh glow skin is fresh and vibrant. Andrea exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // HISPANIC MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "HSP_YA_M_XS_001",
    name: "Alejandro",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Young strong features, warm expression, defined jaw",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Alejandro is an 18-year-old young adult male of Hispanic heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows young strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive with fresh glow skin is fresh and vibrant. Alejandro exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_M_S_001",
    name: "Fernando",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Young strong features, warm expression, defined jaw",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Fernando is a 19-year-old young adult male of Hispanic heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows young strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive with fresh glow skin is fresh and vibrant. Fernando exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_M_L_001",
    name: "Eduardo",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "L",
    height: "180cm (5'11\")",
    weight: "86kg (190lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Young strong features, warm expression, defined jaw",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Eduardo is a 21-year-old young adult male of Hispanic heritage, standing 180cm (5'11\") tall and weighing approximately 86kg (190lbs). He has a sturdy muscular frame with youthful proportions. His face shows young strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive with fresh glow skin is fresh and vibrant. Eduardo exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_M_XL_001",
    name: "Javier",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Young strong features, warm expression, defined jaw",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Javier is a 22-year-old young adult male of Hispanic heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows young strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive with fresh glow skin is fresh and vibrant. Javier exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "HSP_YA_M_2XL_001",
    name: "Pablo",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Hispanic",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Young strong features, warm expression, defined jaw",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown",
    eyeColor: "Warm brown",
    skinTone: "Warm olive with fresh glow",
    fullDescription: "Pablo is a 23-year-old young adult male of Hispanic heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows young strong features, warm expression, and defined jaw. He has short styled cut dark brown hair and warm brown eyes. His warm olive with fresh glow skin is fresh and vibrant. Pablo exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "ASN_YA_F_XS_001",
    name: "Michelle",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Asian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Fresh youthful features, almond eyes, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Michelle is an 18-year-old young adult female of Asian heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows fresh youthful features, almond eyes, and porcelain skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is fresh and vibrant. Michelle exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_F_S_001",
    name: "Christina",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Asian",
    size: "S",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Fresh youthful features, almond eyes, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Christina is a 19-year-old young adult female of Asian heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has a slim athletic frame with youthful proportions. Her face shows fresh youthful features, almond eyes, and porcelain skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is fresh and vibrant. Christina exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_F_L_001",
    name: "Angela",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Asian",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Fresh youthful features, almond eyes, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Angela is a 21-year-old young adult female of Asian heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows fresh youthful features, almond eyes, and porcelain skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is fresh and vibrant. Angela exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_F_XL_001",
    name: "Tiffany",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Asian",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Fresh youthful features, almond eyes, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Tiffany is a 22-year-old young adult female of Asian heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows fresh youthful features, almond eyes, and porcelain skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is fresh and vibrant. Tiffany exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_F_2XL_001",
    name: "Grace",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Asian",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Fresh youthful features, almond eyes, porcelain skin",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Grace is a 23-year-old young adult female of Asian heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows fresh youthful features, almond eyes, and porcelain skin. She has long straight style black hair and dark brown eyes. Her fair with golden undertones skin is fresh and vibrant. Grace exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // ASIAN MALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "ASN_YA_M_XS_001",
    name: "Kevin",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Asian",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Clean young features, almond eyes, smooth complexion",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Kevin is an 18-year-old young adult male of Asian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows clean young features, almond eyes, and smooth complexion. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is fresh and vibrant. Kevin exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_M_M_001",
    name: "Brian",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Asian",
    size: "M",
    height: "175cm (5'9\")",
    weight: "75kg (165lbs)",
    build: "Average athletic frame",
    facialFeatures: "Clean young features, almond eyes, smooth complexion",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Brian is a 20-year-old young adult male of Asian heritage, standing 175cm (5'9\") tall and weighing approximately 75kg (165lbs). He has an average athletic frame with youthful proportions. His face shows clean young features, almond eyes, and smooth complexion. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is fresh and vibrant. Brian exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_M_L_001",
    name: "Daniel",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Asian",
    size: "L",
    height: "180cm (5'11\")",
    weight: "86kg (190lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Clean young features, almond eyes, smooth complexion",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Daniel is a 21-year-old young adult male of Asian heritage, standing 180cm (5'11\") tall and weighing approximately 86kg (190lbs). He has a sturdy muscular frame with youthful proportions. His face shows clean young features, almond eyes, and smooth complexion. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is fresh and vibrant. Daniel exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_M_XL_001",
    name: "Eric",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Asian",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Clean young features, almond eyes, smooth complexion",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Eric is a 22-year-old young adult male of Asian heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows clean young features, almond eyes, and smooth complexion. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is fresh and vibrant. Eric exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "ASN_YA_M_2XL_001",
    name: "Jason",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Asian",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Clean young features, almond eyes, smooth complexion",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Fair with golden undertones",
    fullDescription: "Jason is a 23-year-old young adult male of Asian heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows clean young features, almond eyes, and smooth complexion. He has short styled cut black hair and dark brown eyes. His fair with golden undertones skin is fresh and vibrant. Jason exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN FEMALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "IND_YA_F_XS_001",
    name: "Neha",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Fresh glow, expressive dark eyes, elegant young features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Neha is an 18-year-old young adult female of Indian heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows fresh glow, expressive dark eyes, and elegant young features. She has long flowing style black hair and dark brown eyes. Her warm brown with healthy glow skin is fresh and vibrant. Neha exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_F_S_001",
    name: "Pooja",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indian",
    size: "S",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Fresh glow, expressive dark eyes, elegant young features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Pooja is a 19-year-old young adult female of Indian heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has a slim athletic frame with youthful proportions. Her face shows fresh glow, expressive dark eyes, and elegant young features. She has long flowing style black hair and dark brown eyes. Her warm brown with healthy glow skin is fresh and vibrant. Pooja exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_F_M_001",
    name: "Sneha",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indian",
    size: "M",
    height: "165cm (5'5\")",
    weight: "61kg (134lbs)",
    build: "Average athletic frame",
    facialFeatures: "Fresh glow, expressive dark eyes, elegant young features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Sneha is a 20-year-old young adult female of Indian heritage, standing 165cm (5'5\") tall and weighing approximately 61kg (134lbs). She has an average athletic frame with youthful proportions. Her face shows fresh glow, expressive dark eyes, and elegant young features. She has long flowing style black hair and dark brown eyes. Her warm brown with healthy glow skin is fresh and vibrant. Sneha exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_F_XL_001",
    name: "Shruti",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indian",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Fresh glow, expressive dark eyes, elegant young features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Shruti is a 22-year-old young adult female of Indian heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows fresh glow, expressive dark eyes, and elegant young features. She has long flowing style black hair and dark brown eyes. Her warm brown with healthy glow skin is fresh and vibrant. Shruti exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_F_2XL_001",
    name: "Nikita",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indian",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Fresh glow, expressive dark eyes, elegant young features",
    hairStyle: "Long flowing style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Nikita is a 23-year-old young adult female of Indian heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows fresh glow, expressive dark eyes, and elegant young features. She has long flowing style black hair and dark brown eyes. Her warm brown with healthy glow skin is fresh and vibrant. Nikita exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIAN MALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "IND_YA_M_XS_001",
    name: "Rahul",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indian",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Young strong features, expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Rahul is an 18-year-old young adult male of Indian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows young strong features, expressive eyes, and confident presence. He has short styled cut black hair and dark brown eyes. His warm brown with healthy glow skin is fresh and vibrant. Rahul exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_M_S_001",
    name: "Nikhil",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indian",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Young strong features, expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Nikhil is a 19-year-old young adult male of Indian heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows young strong features, expressive eyes, and confident presence. He has short styled cut black hair and dark brown eyes. His warm brown with healthy glow skin is fresh and vibrant. Nikhil exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_M_M_001",
    name: "Karan",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indian",
    size: "M",
    height: "175cm (5'9\")",
    weight: "75kg (165lbs)",
    build: "Average athletic frame",
    facialFeatures: "Young strong features, expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Karan is a 20-year-old young adult male of Indian heritage, standing 175cm (5'9\") tall and weighing approximately 75kg (165lbs). He has an average athletic frame with youthful proportions. His face shows young strong features, expressive eyes, and confident presence. He has short styled cut black hair and dark brown eyes. His warm brown with healthy glow skin is fresh and vibrant. Karan exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_M_XL_001",
    name: "Siddharth",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indian",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Young strong features, expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Siddharth is a 22-year-old young adult male of Indian heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows young strong features, expressive eyes, and confident presence. He has short styled cut black hair and dark brown eyes. His warm brown with healthy glow skin is fresh and vibrant. Siddharth exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IND_YA_M_2XL_001",
    name: "Varun",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indian",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Young strong features, expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm brown with healthy glow",
    fullDescription: "Varun is a 23-year-old young adult male of Indian heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows young strong features, expressive eyes, and confident presence. He has short styled cut black hair and dark brown eyes. His warm brown with healthy glow skin is fresh and vibrant. Varun exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN FEMALE - Missing: XS, M, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "SEA_YA_F_XS_001",
    name: "Thao",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Fresh soft features, warm eyes, gentle youthful beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Thao is an 18-year-old young adult female of Southeast Asian heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows fresh soft features, warm eyes, and gentle youthful beauty. She has long straight style black hair and dark brown eyes. Her light tan with warm glow skin is fresh and vibrant. Thao exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_F_M_001",
    name: "Kim",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "M",
    height: "165cm (5'5\")",
    weight: "61kg (134lbs)",
    build: "Average athletic frame",
    facialFeatures: "Fresh soft features, warm eyes, gentle youthful beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Kim is a 20-year-old young adult female of Southeast Asian heritage, standing 165cm (5'5\") tall and weighing approximately 61kg (134lbs). She has an average athletic frame with youthful proportions. Her face shows fresh soft features, warm eyes, and gentle youthful beauty. She has long straight style black hair and dark brown eyes. Her light tan with warm glow skin is fresh and vibrant. Kim exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_F_L_001",
    name: "Hanh",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Fresh soft features, warm eyes, gentle youthful beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Hanh is a 21-year-old young adult female of Southeast Asian heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows fresh soft features, warm eyes, and gentle youthful beauty. She has long straight style black hair and dark brown eyes. Her light tan with warm glow skin is fresh and vibrant. Hanh exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_F_XL_001",
    name: "Sumalee",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Fresh soft features, warm eyes, gentle youthful beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Sumalee is a 22-year-old young adult female of Southeast Asian heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows fresh soft features, warm eyes, and gentle youthful beauty. She has long straight style black hair and dark brown eyes. Her light tan with warm glow skin is fresh and vibrant. Sumalee exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_F_2XL_001",
    name: "Nari",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Fresh soft features, warm eyes, gentle youthful beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Nari is a 23-year-old young adult female of Southeast Asian heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows fresh soft features, warm eyes, and gentle youthful beauty. She has long straight style black hair and dark brown eyes. Her light tan with warm glow skin is fresh and vibrant. Nari exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // SOUTHEAST ASIAN MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "SEA_YA_M_XS_001",
    name: "Tran",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Young warm features, friendly eyes, approachable expression",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Tran is an 18-year-old young adult male of Southeast Asian heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows young warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with warm glow skin is fresh and vibrant. Tran exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_M_S_001",
    name: "Vinh",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Young warm features, friendly eyes, approachable expression",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Vinh is a 19-year-old young adult male of Southeast Asian heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows young warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with warm glow skin is fresh and vibrant. Vinh exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_M_L_001",
    name: "Dao",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "L",
    height: "180cm (5'11\")",
    weight: "86kg (190lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Young warm features, friendly eyes, approachable expression",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Dao is a 21-year-old young adult male of Southeast Asian heritage, standing 180cm (5'11\") tall and weighing approximately 86kg (190lbs). He has a sturdy muscular frame with youthful proportions. His face shows young warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with warm glow skin is fresh and vibrant. Dao exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_M_XL_001",
    name: "Prem",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Young warm features, friendly eyes, approachable expression",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Prem is a 22-year-old young adult male of Southeast Asian heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows young warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with warm glow skin is fresh and vibrant. Prem exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "SEA_YA_M_2XL_001",
    name: "Arun",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Southeast Asian",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Young warm features, friendly eyes, approachable expression",
    hairStyle: "Short styled cut",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Light tan with warm glow",
    fullDescription: "Arun is a 23-year-old young adult male of Southeast Asian heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows young warm features, friendly eyes, and approachable expression. He has short styled cut black hair and dark brown eyes. His light tan with warm glow skin is fresh and vibrant. Arun exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "MDE_YA_F_XS_001",
    name: "Aisha",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "Striking dark eyes, fresh elegant features, vibrant beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Aisha is an 18-year-old young adult female of Middle Eastern heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows striking dark eyes, fresh elegant features, and vibrant beauty. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm vibrant glow skin is fresh and vibrant. Aisha exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_F_S_001",
    name: "Dina",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Striking dark eyes, fresh elegant features, vibrant beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Dina is a 19-year-old young adult female of Middle Eastern heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has a slim athletic frame with youthful proportions. Her face shows striking dark eyes, fresh elegant features, and vibrant beauty. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm vibrant glow skin is fresh and vibrant. Dina exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_F_L_001",
    name: "Lina",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "Striking dark eyes, fresh elegant features, vibrant beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Lina is a 21-year-old young adult female of Middle Eastern heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows striking dark eyes, fresh elegant features, and vibrant beauty. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm vibrant glow skin is fresh and vibrant. Lina exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_F_XL_001",
    name: "Mira",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "Striking dark eyes, fresh elegant features, vibrant beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Mira is a 22-year-old young adult female of Middle Eastern heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows striking dark eyes, fresh elegant features, and vibrant beauty. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm vibrant glow skin is fresh and vibrant. Mira exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_F_2XL_001",
    name: "Rana",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Middle Eastern",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "Striking dark eyes, fresh elegant features, vibrant beauty",
    hairStyle: "Long flowing style",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Rana is a 23-year-old young adult female of Middle Eastern heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows striking dark eyes, fresh elegant features, and vibrant beauty. She has long flowing style dark brown to black hair and dark brown eyes. Her olive with warm vibrant glow skin is fresh and vibrant. Rana exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // MIDDLE EASTERN MALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "MDE_YA_M_XS_001",
    name: "Ali",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "Strong young features, dark expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Ali is an 18-year-old young adult male of Middle Eastern heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows strong young features, dark expressive eyes, and confident presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm vibrant glow skin is fresh and vibrant. Ali exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_M_S_001",
    name: "Rami",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "Strong young features, dark expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Rami is a 19-year-old young adult male of Middle Eastern heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows strong young features, dark expressive eyes, and confident presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm vibrant glow skin is fresh and vibrant. Rami exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_M_L_001",
    name: "Sami",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "L",
    height: "180cm (5'11\")",
    weight: "86kg (190lbs)",
    build: "Sturdy muscular frame",
    facialFeatures: "Strong young features, dark expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Sami is a 21-year-old young adult male of Middle Eastern heritage, standing 180cm (5'11\") tall and weighing approximately 86kg (190lbs). He has a sturdy muscular frame with youthful proportions. His face shows strong young features, dark expressive eyes, and confident presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm vibrant glow skin is fresh and vibrant. Sami exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_M_XL_001",
    name: "Nabil",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "Strong young features, dark expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Nabil is a 22-year-old young adult male of Middle Eastern heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows strong young features, dark expressive eyes, and confident presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm vibrant glow skin is fresh and vibrant. Nabil exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "MDE_YA_M_2XL_001",
    name: "Kareem",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Middle Eastern",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "Strong young features, dark expressive eyes, confident presence",
    hairStyle: "Short styled cut",
    hairColor: "Dark brown to black",
    eyeColor: "Dark brown",
    skinTone: "Olive with warm vibrant glow",
    fullDescription: "Kareem is a 23-year-old young adult male of Middle Eastern heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows strong young features, dark expressive eyes, and confident presence. He has short styled cut dark brown to black hair and dark brown eyes. His olive with warm vibrant glow skin is fresh and vibrant. Kareem exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS FEMALE - Missing: XS, S, L, XL, 2XL (5)
  // ============================================================================
  {
    id: "IDG_YA_F_XS_001",
    name: "Sierra",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "XS",
    height: "155cm (5'1\")",
    weight: "48kg (106lbs)",
    build: "Petite slim frame",
    facialFeatures: "High cheekbones, youthful strength, natural vibrant beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Sierra is an 18-year-old young adult female of Indigenous heritage, standing 155cm (5'1\") tall and weighing approximately 48kg (106lbs). She has a petite slim frame with youthful proportions. Her face shows high cheekbones, youthful strength, and natural vibrant beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is fresh and vibrant. Sierra exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_F_S_001",
    name: "Autumn",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "S",
    height: "160cm (5'3\")",
    weight: "54kg (119lbs)",
    build: "Slim athletic frame",
    facialFeatures: "High cheekbones, youthful strength, natural vibrant beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Autumn is a 19-year-old young adult female of Indigenous heritage, standing 160cm (5'3\") tall and weighing approximately 54kg (119lbs). She has a slim athletic frame with youthful proportions. Her face shows high cheekbones, youthful strength, and natural vibrant beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is fresh and vibrant. Autumn exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_F_L_001",
    name: "Willow",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "L",
    height: "170cm (5'7\")",
    weight: "70kg (154lbs)",
    build: "Sturdy athletic frame",
    facialFeatures: "High cheekbones, youthful strength, natural vibrant beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Willow is a 21-year-old young adult female of Indigenous heritage, standing 170cm (5'7\") tall and weighing approximately 70kg (154lbs). She has a sturdy athletic frame with youthful proportions. Her face shows high cheekbones, youthful strength, and natural vibrant beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is fresh and vibrant. Willow exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_F_XL_001",
    name: "Raven",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "XL",
    height: "173cm (5'8\")",
    weight: "82kg (181lbs)",
    build: "Large athletic frame",
    facialFeatures: "High cheekbones, youthful strength, natural vibrant beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Raven is a 22-year-old young adult female of Indigenous heritage, standing 173cm (5'8\") tall and weighing approximately 82kg (181lbs). She has a large athletic frame with youthful proportions. Her face shows high cheekbones, youthful strength, and natural vibrant beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is fresh and vibrant. Raven exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_F_2XL_001",
    name: "River",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Female",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "175cm (5'9\")",
    weight: "95kg (209lbs)",
    build: "Plus size frame",
    facialFeatures: "High cheekbones, youthful strength, natural vibrant beauty",
    hairStyle: "Long straight style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "River is a 23-year-old young adult female of Indigenous heritage, standing 175cm (5'9\") tall and weighing approximately 95kg (209lbs). She has a plus size frame with youthful proportions. Her face shows high cheekbones, youthful strength, and natural vibrant beauty. She has long straight style black hair and dark brown eyes. Her warm reddish-brown skin is fresh and vibrant. River exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },

  // ============================================================================
  // INDIGENOUS MALE - Missing: XS, S, M, XL, 2XL (5)
  // ============================================================================
  {
    id: "IDG_YA_M_XS_001",
    name: "Hunter",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "XS",
    height: "163cm (5'4\")",
    weight: "57kg (126lbs)",
    build: "Slim lean frame",
    facialFeatures: "High cheekbones, strong young features, confident bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Hunter is an 18-year-old young adult male of Indigenous heritage, standing 163cm (5'4\") tall and weighing approximately 57kg (126lbs). He has a slim lean frame with youthful proportions. His face shows high cheekbones, strong young features, and confident bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is fresh and vibrant. Hunter exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_M_S_001",
    name: "Hawk",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "S",
    height: "168cm (5'6\")",
    weight: "65kg (143lbs)",
    build: "Slim athletic frame",
    facialFeatures: "High cheekbones, strong young features, confident bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Hawk is a 19-year-old young adult male of Indigenous heritage, standing 168cm (5'6\") tall and weighing approximately 65kg (143lbs). He has a slim athletic frame with youthful proportions. His face shows high cheekbones, strong young features, and confident bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is fresh and vibrant. Hawk exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_M_M_001",
    name: "Bear",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "M",
    height: "175cm (5'9\")",
    weight: "75kg (165lbs)",
    build: "Average athletic frame",
    facialFeatures: "High cheekbones, strong young features, confident bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Bear is a 20-year-old young adult male of Indigenous heritage, standing 175cm (5'9\") tall and weighing approximately 75kg (165lbs). He has an average athletic frame with youthful proportions. His face shows high cheekbones, strong young features, and confident bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is fresh and vibrant. Bear exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_M_XL_001",
    name: "Wolf",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "XL",
    height: "183cm (6'0\")",
    weight: "98kg (216lbs)",
    build: "Large muscular frame",
    facialFeatures: "High cheekbones, strong young features, confident bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Wolf is a 22-year-old young adult male of Indigenous heritage, standing 183cm (6'0\") tall and weighing approximately 98kg (216lbs). He has a large muscular frame with youthful proportions. His face shows high cheekbones, strong young features, and confident bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is fresh and vibrant. Wolf exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  },
  {
    id: "IDG_YA_M_2XL_001",
    name: "Storm",
    age: "Young Adult",
    ageRange: "18-24",
    sex: "Male",
    ethnicity: "Indigenous",
    size: "2XL",
    height: "185cm (6'1\")",
    weight: "113kg (249lbs)",
    build: "Very large frame",
    facialFeatures: "High cheekbones, strong young features, confident bearing",
    hairStyle: "Long traditional style",
    hairColor: "Black",
    eyeColor: "Dark brown",
    skinTone: "Warm reddish-brown",
    fullDescription: "Storm is a 23-year-old young adult male of Indigenous heritage, standing 185cm (6'1\") tall and weighing approximately 113kg (249lbs). He has a very large frame with youthful proportions. His face shows high cheekbones, strong young features, and confident bearing. He has long traditional style black hair and dark brown eyes. His warm reddish-brown skin is fresh and vibrant. Storm exudes youthful energy and contemporary style.",
    version: "2.0",
    createdDate: "2025-12-28"
  }
];

// Total: 78 Young Adult Personas
export default missingYoungAdultPersonas;
